nix-community/infra

build01/nixpkgs-update.nix, nix/sources.json
Was able to run the script locally, and works as expected with a checkout of nixpkgs.
This does require a local checkout of nixpkgs though.
example result file:
```
$ cat ./package-to-update.txt | head -20
picard 2.2.3 2.3.1 https://pypi.org/project/picard/
friture 0.37 0.38 https://pypi.org/project/friture/
mopidy 2.3.1 3.0.1 https://pypi.org/project/mopidy/
tzupdate 1.5.0 2.0.0 https://pypi.org/project/tzupdate/
menumaker 0.99.11 1.4.1 https://pypi.org/project/menumaker/
buku 4.2.2 4.3 https://pypi.org/project/buku/
cozy 0.6.7 1.0 https://pypi.org/project/cozy/
guake 3.6.3 3.7.0 https://pypi.org/project/guake/
kitty 0.16.0 1.2.0 https://pypi.org/project/kitty/
udiskie 1.7.7 2.1.0 https://pypi.org/project/udiskie/
jrnl 1.9.8 2.3.1 https://pypi.org/project/jrnl/
hovercraft 2.6 2.7 …
```
=> Add nixpkgs-update-pypi-release

build01/nixpkgs-update.nix, nix/sources.json
includes https://github.com/jonringer/nixpkgs-update-pypi-releases/commit/cf72f9a94b0ccc306c025eba222a70456378433d which doesn't use the `-f .` args to nix-env, and instead generates the list off NIX_PATH
=> nixpkgs-update-pypi-releases: use NIX_PATH and re-enable

nix/sources.json
for the pypi releases, this prevents creating python-3.6 drv-names, which is causing a lot of the packages to be filtered out.
=> Update nixpkgs to current master

deployment.nix, secrets.nix
The SSH private key file needs to have a last empty new
line. Otherwise, SSH fails with:
Load key "/path/to/key": invalid format
=> secrets: only remove suffix "\n" for the buildkite token

nix/sources.json
The version in #25 was mostly to get the deployment working. I think this version is ready for a test run on nixpkgs. It currently only reacts to PRs where it is summoned in the initial PR message.
- slash commands instead of @mentions
- some fixes
- training wheels removed (no toy commands anymore, does not run on issues)
- logs exceptions instead of crashing the entire server
- some fixes, improved messages
=> marvin-mk2: update

nix/sources.json
What would a first deploy be without a typo. Only change is
https://github.com/timokau/marvin-mk2/pull/14 ("Fix status
terminology").
We should get the instructions in order before asking people to test it. @ryantm, this time it really should be a simple deploy :)
=> marvin: update

terraform/cloudflare_nix-community_org.tf
What do you think of this?
It would allow to, for example, have https://nur.nix-community.org/ instead of https://nix-community.github.io/nur-search/
/cc @Mic92
=> add CNAME for *.nix-community.org to github pages

build01/hydra-declarative-projects.nix
The Hydra declarative project configuration is not part of the Redoxpkgs repository yet (see https://github.com/nix-community/redoxpkgs/pull/2).
=> hydra: add Redoxpkgs project

roles/security.nix
Encourage users to SSH as their own users. User accounts were not able
to `sudo` as they don't have a password associated to them.
=> roles/security: allow sudo without password

roles/nix-community-cache.nix
There is one more fixed by https://github.com/NixOS/nixpkgs/pull/117925
=> nix-community-cache: fix causes of warnings in the log

nix/sources.json, roles/nix-community-cache.nix
We've had instability with the former, and it turns out Cachix has
gained some functionality that's better for our use case.
=> Migrate from `queued-build-hook` to `cachix watch-store`

services/hydra/default.nix
Because the Hydra version containing this patch is not in nixpkgs yet.
Note this is already deployed...
=> hydra: apply a patch to fix a jobset evaluation issue

services/hydra/declarative-projects.nix
This adds hydra ci jobs for the rust-for-linux linux tree.
I spoke with @Mic92 about adding this to the nix-community hydra.
=> add rust-for-linux hydra job

build01/configuration.nix, deployment.nix, roles/gitlab-runner.nix
emacs-overlay uses now github actions successfully for a while: https://github.com/nix-community/emacs-overlay/actions
=> build01: shutdown gitlab runner

services/hydra/create-declarative-project.sh
This is because of an Hydra API change.
=> Update declarative project creation

nix/overlays.nix, nix/sources.json
nixopsUnstable changed a lot and appears to be broken in various ways. Like it doesn't respect the --state flag anymore and choosing the memory or legacy state backends doesn't seem to work. Switching to nixops isn't an option either since it is broken on master.
This adds a new niv pin for nixops that pins it to the last master rev we were on that worked.
=> pin nixopsUnstable to working version

build03/configuration.nix, services/hydra/default.nix
This no longer requires stopping hydra when doing nix-gc to avoid
race conditions in cachix-watch store.
=> hydra: upload cachix directly

terraform/hydra-jobsets.tf
Kittybox moved to Sourcehut. Update the flake URI and homepage URI to reflect that.
=> hydra-jobsets.tf: update canonical Kittybox source

roles/builder/users.nix
As many derivations require in-fact to be trusted (input-addressed ones, NixOS tests, non-signed stuff), I am more often forced to disable the builder, so it is earlier than I expected, but I would like to request the trusted status.
Of course, if this is not the good time, we can let this PR open and merge when the community feels it is the good time to do it.
In the meantime, thank you for everything you do :)
=> builder/users: make raitobezarius trusted

flake.lock, flake.nix
Update hercules-ci-agent to `master` to help fix nix-community/dream2nix-nodejs-auto, https://github.com/hercules-ci/support/issues/67.
=> hercules-ci-agent: Use master

users/mic92.nix
I've resolved yesterday's issue and I don't need access to the local hercules-ci-agent logs for the time being.
This reverts commit 728948a8011d7ec3297dad1d14ef5c3b9a35450f.
Thanks @Mic92 for making troubleshooting easy!
=> Revert "add roberth to server"

bors.toml
bors defaults to including the text from the PR body in the merge commit message but also picks up the hidden text in PR template, see https://github.com/nix-community/infra/commit/871821115399a9948da43ec1adfe0caf6c114934
Easier to drop the entire PR body and just use the PR title.
=> bors: fix merge commit message

ci.nix, flake.lock, flake.nix, roles/users.nix
Probably not much need for effects deployment with hourly auto upgrades. (Though maybe we should set up something to monitor the auto upgrades?)
Looks like the ssh key is in sops but someone else will need to remove that.
=> ci: remove effects deployment

README.md
healthchecks.io ping was removed in dc4a41108551b400dbf6012e7fb8a0370880bc29
=> README.md: minor updates

services/hound/hound.json, services/hound/update-hound.py
~~With this we do lose a few repos, e.g. https://github.com/nix-community/bundix, https://github.com/nix-community/luarocks-nix but defaulting to not including forks seems sensible. Perhaps could include them via an allowlist instead?~~
Switched to allowing some forks.
=> hound: only include repos that aren't archived or forked

terraform/hydra-projects.tf
both of these have been inactive for over a year
=> hydra: disable nix-data, redoxpkgs

flake.lock, flake.nix
agent has been patched in nixpkgs https://github.com/NixOS/nixpkgs/commit/34f6edc870a420f1edc0b32cf85b8b5f3ee2949c
~~need to wait for it to land in nixos-unstable-small.~~
https://nixpk.gs/pr-tracker.html?pr=199424
=> switch to nixpkgs hercules-ci-agent

build02/configuration.nix
Might save a bit of memory, don't really need it on both build02 and build03. 
Also aligns the hercules and hydra config (build03/build04).
=> build02: remove hercules

build02/nixpkgs-update.nix
I am very ignorant about how all this infrastructure works, so I have no idea if I'm suggesting the right thing here.
However, looking at https://r.ryantm.com/log/, it seems that packages earlier in the alphabet get updated more frequently than packages later in the alphabet. I imagine something like the following is happening:
* Each of the fetchers in this file is outputting an alphabetical list of packages to update to the FIFO.
* The workers are processing those packages in order.
* Before the workers finish processing the entire queue, something happens to the infrastructure (a nixpkgs update, maybe?) that respawns everything.
* The workers start again at the beginning of the alphabet.
I wanted to make sure I wasn't imagining things, so I collected some data. Here's my …
=> build02: correct for alphabetic bias in updates

README.md, ci.sh, treefmt.nix
`ci.sh` seems a bit redundant. (also needs aarch64 and x86_64 to build)
Removing shell from treefmt as now it isn't needed for anything in the repo.
=> treefmt: remove shell

flake.nix, roles/nix-daemon.nix
=> nix-daemon: do not expose flake-inputs.prom anymore

docs/_config.yml
currently this is show the description from the infra repo
=> docs/_config.yml: disable description

terraform/cloudflare_nix-community_org.tf
=> terraform/cloudflare: add dns for darwin builder

.github/settings.yml
this wasn't originally enabled
=> .github/settings.yml: disable "Require branches to be up to date before merging"

terraform/cloudflare_nix-community_org.tf
This gives the domain the verified badge on https://github.com/nix-community.
https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-organization-settings/verifying-or-approving-a-domain-for-your-organization
=> terraform/cloudflare: add nix-community.org verification for github

.github/labeler.yml, .github/settings.yml, .github/workflows/flake-updates-nixpkgs-update.yml
cc @adisbladis @Mic92 @ryantm @zimbatm 
@ryantm Is the action a good enough workaround for you not being able to push `nixpkgs-update` updates to master? Can run it manually on github or via cli.
https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow?tool=webui
```
export GITHUB_TOKEN=<token with repo write access>
gh workflow run flake-updates-nixpkgs-update.yml --repo nix-community/infra
```
=> change to PR only workflow 

terraform/cloudflare.tf, terraform/locals.tf, terraform/secrets.yaml, terraform/terraform_cloud.tf
=> Cloudflare admins

flake.lock, flake.nix
=> flake: `treefmt-nix` follow nixpkgs

terraform/cloudflare_nix-community_org.tf
Fix the DNS records so we can use the email forwarding service from
Gandi.
=> terraform: use Gandi for email

build04/configuration.nix
cc @zowoq
I was greeted by a EDK2 EFI shell and had to boot grub manually.
Systemd-boot meanwhile seems to work fine and also installs a default boot loader path that would work even if efivars is not set.
bors merge
=> build04: switch to systemd-boot

tasks.py
in the nix store timestamps are not correct.
=> tasks.py: fix rsync ignoring some file changes

.github/settings.yml
https://github.com/orgs/nix-community/teams/infra
https://github.com/nix-community/infra#nix-community-administrators
I was going to rename `@nix-community/infra` to better match the role of this team.
cc @nix-community/infra
=> .github/settings.yml: rename team, infra -> admin

build02/nixpkgs-update.nix, flake.lock, flake.nix
86f4428fe017140f2b4c849cda2cd6c26a9ff705
has been disabled for a couple of months now
=> remove nixpkgs-update-pypi-releases

build02/nixpkgs-update.nix
@mic92 The oom's seem to have settled down, shall we try adding another worker?
=> build02/nixpkgs-update: enable another worker

build02/nixpkgs-update.nix
uses too much memory
This reverts commit e1fa02c23fa1e166064530576b1baeb522f55223.
=> Revert "build02/nixpkgs-update: enable another worker"

build03/configuration.nix
post-build-hook is failing and blocking builds that are scheduled on build03
=> build03: disable hydra

build03/configuration.nix, roles/nix-community-cache/secrets.yaml, roles/watch-store.nix, services/hydra/default.nix
watch-store seems to be more efficient than the hook.
https://github.com/cachix/cachix/blob/master/cachix/CHANGELOG.md#13---2023-03-06
with >=1.3 it defaults to 8 jobs
=> remove post-build-hook, switch to cachix watch-store

flake.nix, treefmt.nix
By importing the config on the treefmt module level, it makes the config more flat, and also compatible with non-flake-parts users.
=> treefmt: flatten the config

build02/nixpkgs-update.nix
Same as https://github.com/nix-community/infra/pull/514, seems cachix has been causing the updates to fail as well.
cc @ryantm
=> build02/nixpkgs-update: pin cachix to 1.3.3

roles/watch-store.nix
=> roles/watch-store: always restart

build04/configuration.nix
`/boot` is starting to fill up again.
=> build04: set systemd-boot.configurationLimit

treefmt.nix
This mostly avoids my original objection to having deadnix enabled as now it isn't all or nothing. We can keep dead/commented out code without needing to disable the other nix formatters.
I think it's possible that the deadnix and nix formatters could conflict but that doesn't seem like too much of a hassle.
=> treefmt: add deadnix

roles/auto-upgrade.nix
sometimes upgrades are skipped until the next hour
=> roles/auto-upgrade: set tarball-ttl

docs/security.md, mkdocs.yml
Easier to keep it in this repo and have https://github.com/nix-community/.github/blob/master/SECURITY.md link to it.
=> docs: add security policy

shell.nix, tasks.py
- drop treefmt, accessible via `nix fmt`
- drop mkdocs, accessible via `inv mkdocs`
this halves the size of the devshell
=> shell: refactor, reduce size

terraform/flake.lock
Flake lock file updates:
• Updated input 'nixpkgs':
'github:NixOS/nixpkgs/1474943fd91fbe5567f7582acf568e0f999f4af1' (2023-03-14)
→ 'github:NixOS/nixpkgs/5751551558d7896ffb30ff3d709b4943bb3eafa8' (2023-05-04)
Terraform updates:
terraform: 1.4.0 → 1.4.6
terraform-provider-cloudflare: 4.1.0 → 4.5.0
terraform-provider-tfe: 0.42.0 → 0.44.1
=> terraform/flake.lock: Update

roles/auto-upgrade.nix
spread out reboots so every machine isn't offline at the same time
=> roles/auto-upgrade: separate reboot from upgrade

secrets.yaml
After this is merged I'll make `nix-infra-bot` an org owner and generate an token with org permissions to use with terraform in https://github.com/nix-community/infra/pull/544.
I'll do the same again in another PR for gitlab.
=> secrets.yaml: add nix-infra-bot

build02/nixpkgs-update.nix, roles/watch-store.nix
cachix was reverted to 1.3.3 in nixpkgs: https://github.com/NixOS/nixpkgs/commit/2b9ec87c4e4380a420923a2610289bc9444ee132
=> unpin cachix

.github/workflows/labels.yml
=> .github/workflows/labels.yml: remove `repo-token`

build01/configuration.nix, build01/default.nix, build02/configuration.nix, build02/default.nix, build03/configuration.nix, build03/default.nix, build04/configuration.nix, build04/default.nix, flake.nix, roles/common.nix
Inject the inputs in specialArgs so they can be used in the modules directly. This allows us to split up the top-level flake as well.
=> flake: split up per host

flake.nix
This only needs to be built by CI on x86_64-linux for deploying to github pages.
=> flake: build packages on x86_64-linux only

build03/configuration.nix, services/hydra/default.nix
Seems watch-store in cachix 1.5 has problems. Cachix can push paths so using post-build-hook and nixpkgs-update on build02 works.
```
May 26 05:55:34 build03 systemd[1]: cachix-watch-store-agent.service: Failed with result 'exit-code'.
May 26 05:55:34 build03 systemd[1]: cachix-watch-store-agent.service: Consumed 152ms CPU time, received 4.8K IP traffic, sent 1.6K IP traffic.
May 26 05:55:35 build03 systemd[1]: cachix-watch-store-agent.service: Scheduled restart job, restart counter is at 1045.
May 26 05:55:35 build03 systemd[1]: Stopped Cachix watch store Agent.
May 26 05:55:35 build03 systemd[1]: cachix-watch-store-agent.service: Consumed 152ms CPU time, received 4.8K IP traffic, sent 1.6K IP traffic.
May 26 05:55:35 build03 systemd[1]: Started Cachix watch store Agent.
May 26 05:55:36 …
```
=> switch back to post-build-hook

hosts/darwin02/configuration.nix, hosts/darwin02/telegraf.nix
This is a basic version of the srvos telegraf module, dropped everything that requires sudo or is linux specific.
~~Also needs to be added in https://github.com/Mic92/dotfiles/blob/main/nixos/eva/modules/prometheus/default.nix#L118.~~ https://github.com/Mic92/dotfiles/pull/681
=> hosts/darwin02: add telegraf

terraform/cloudflare_nix-community_org.tf
We removed hound seven weeks ago so I think anyone using it will have noticed the redirect by now.
Also github moved code search behind a login a couple of weeks ago so the redirect is less useful than it was originally.
I'll delete the redirect once the PR is merged.
=> terraform/cloudflare: remove search.nix-community.org

hosts/build03/configuration.nix, modules/nixos/hydra/default.nix
This reverts commit 94de107c309b3d1b0af304553c7f40c2bd39874c.
watch-store seems to be working again with cachix 1.6
=> Revert "switch back to post-build-hook"

.github/mergify.yml, .github/settings.yml, .github/workflows/flake-updates-nixpkgs-update.yml, flake.nix
this lets us consolidate automerges and remove GH_TOKEN_FOR_UPDATES
not using mergify merge queue function as we'd need to modify the effects.
=> switch to mergify

flake.lock
https://github.com/numtide/srvos/pull/199
```
[mic92@web01:~]$ sudo systemctl cat cloud-init | grep --color xfs
Environment="PATH=/nix/store/z3raph8hi3z246cvian7kcx9yynwwnz5-cloud-init-23.2.1/bin:/nix/store/x7kkkxxl84xjynyqw8gv89nd17myril2-iproute2-6.3.0/bin:/nix/store/ymq5hsa5lrsg5an8w2fs09na0djbrk38-net-tools-2.10/bin:/nix/store/8x654pvf2g43sqkc0y2p4l77rscrsnnd-openssh-9.3p1/bin:/nix/store/zhd1016mmay8ci08c5s99xd6wb1b0r0q-shadow-4.13/bin:/nix/store/gpwv7ynjx4h3k1viw96yfwxsid0ml9wc-util-linux-2.39-bin/bin:/nix/store/zb807hx0sxl5lf8kn9mhhfakxcjls5lb-busybox-1.36.1/bin:/nix/store/d3166x4xa84wv69vm5icqj970gf1yjj4-xfsprogs-6.3.0-bin/bin:/nix/store/c2bq8xsayc90s33fd5xbm1vh5lrmwcfq-coreutils-9.3/bin:/nix/store/dq11g3lzkl5bxrjy9y6x1pjxkxx6z91f-findutils-4.9.0/bin:/nix/store/yw3g789y5fpmxbzgkhs4n …
```
=> Fix xfsprogs missing in cloud-init

modules/nixos/community-builder/keys/lily, modules/nixos/community-builder/users.nix
I'm already in the aarch64 and darwin community builders, but being able to do x86_64-linux builds on a remote builder to review and create nixpkgs PRs will probably be a good thing for my laptop (especially cross testing and such...)
Let me know if I need to provide more info to use the community builder, thank you!
=> builder/users: add lily

docs/open-collective.md
I couldn't find a way to set the height in their docs, so hack it.
=> docs: fix OpenCollective banner height

modules/darwin/common/default.nix, modules/darwin/common/flake-inputs.nix
This is useful as we're currently deploying the darwin hosts manually.
=> modules/darwin/common: add flake-inputs

dev/effect.nix, hosts/build01/configuration.nix
https://app.cachix.org/organization/nix-community/deploy/workspace/community-infra/agent/build01
Added this in https://github.com/nix-community/infra/pull/688 just to try it out, can switch back to the standard update method now.
I'll probably switch to using `cachix deploy` like this for our darwin machines once the CI issues are resolved.
Needs to be deployed manually to `build01` after this PR is merged.
=> Revert "build01: cachix deploy"

modules/darwin/builder.nix
- drop unnecessary description and group
- use postActivation to give build user ssh access
=> modules/darwin/builder: various

hosts/darwin02/configuration.nix, hosts/darwin03/configuration.nix, modules/darwin/common/default.nix
As we only have hetzner machines at the moment we can share this user/keys between hosts but we'll need to change it if we add a non-hetzner machine.
=> modules/darwin/common: refactor authorizedKeys

docs/sponsors.md
This will break the markdown but it'll fix the website.
https://nix-community.org/sponsors/
https://github.com/nix-community/infra/blob/109220365d467dd36998a1b21482336deef769cc/docs/sponsors.md
=> docs/sponsors.md: fix link

modules/nixos/monitoring/alert-rules.nix
Separate rule for the matrix service to improve visibility.
=> modules/nixos/monitoring/alert-rules: add matrix-alertmanager-receiver

hosts/build04/configuration.nix
we have aarch64 support in nixos-anywhere
=> build04: kexec argument is no longer needed

modules/nixos/community-builder/packages.nix
I would like to propose to add `mosh` ([mosh.org](https://mosh.org/)) to the community builder.
I like to keep my ssh sessions via suspends, and this helps.
=> community-builder packages: Add mosh

modules/nixos/monitoring/prometheus.nix
I thought this was disabled by default in nixpkgs but apparently not.
=> modules/nixos/monitoring: disable alertmanager clustering

hosts/web01/lemmy.nix
Seems like a bit of a hammer but it did work.
> https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Upholds=
> Configures dependencies similar to Wants=, but as long as this unit is up, all units listed in Upholds= are started whenever found to be inactive or failed, and no job is queued for them. While a Wants= dependency on another unit has a one-time effect when this units started, a Upholds= dependency on it has a continuous effect, constantly restarting the unit if necessary. This is an alternative to the Restart= setting of service units, to ensure they are kept running whatever happens. The restart happens without delay, and usual per-unit rate-limit applies.
=> web01: add `Upholds` to lemmy for pict-rs

docs/monitoring.md, modules/nixos/monitoring/default.nix, modules/nixos/monitoring/prometheus.nix, terraform/cloudflare_nix-community_org.tf
This seems to be a bit neater than having multiple subdomains, etc.
Mostly copied from [nixos-org-configurations](https://github.com/NixOS/nixos-org-configurations/blob/3ca70f40caf1d5099b9382e2aa15ba863b8aad67/delft/eris.nix#L80).
=> move alertmanager, prometheus under monitoring.nix-community.org

docs/monitoring.md, modules/nixos/monitoring/default.nix, modules/nixos/monitoring/prometheus.nix, terraform/cloudflare_nix-community_org.tf
Reverts nix-community/infra#801
Reverting this as alertmanager isn't receiving alerts from prometheus.
=> Revert "move alertmanager, prometheus under monitoring.nix-community.org"

modules/shared/nix-daemon.nix
min-free, max-free and max-freed numbers are from https://github.com/NixOS/nixos-org-configurations/blob/master/macs/nix-darwin.nix, I think they're fine for all the hosts.
=> modules/shared/nix-daemon: fix `asGB`

flake.nix, hosts/build01/configuration.nix, hosts/build02/configuration.nix, hosts/build03/configuration.nix, hosts/build04/configuration.nix, hosts/darwin02/configuration.nix, hosts/darwin03/configuration.nix, modules/darwin/builder.nix, modules/nixos/builder.nix, modules/shared/builder.nix, modules/shared/nix-daemon.nix
Easier to review and merge the remote-builder module commit first in https://github.com/nix-community/infra/pull/815.
___
Noticed `loginLimits` in [nixos-org-configurations](https://github.com/NixOS/nixos-org-configurations/blob/3ca70f40caf1d5099b9382e2aa15ba863b8aad67/delft/common.nix#L70) when I was looking for their `nix.gc` config.
[srvos](https://github.com/numtide/srvos/blob/main/nixos/roles/nix-remote-builder.nix#L26) sets 20480 in the remote builder module so I'll use that.
---
min-free, max-free and max-freed numbers are from https://github.com/NixOS/nixos-org-configurations/blob/master/macs/nix-darwin.nix.
=> modules: add darwin/nixos builder, update min-free/max-free, increase open file limit

modules/shared/builder.nix
Thought I'd already fixed this but must have reverted it when refactoring.
=> modules/shared/builder: fix max-freed size

modules/nixos/monitoring/matrix-hook.nix
Should be able to merge this after tomorrows flake update.
=> modules/nixos/monitoring/matrix-hook: use package from nixpkgs

flake.lock, flake.nix
Blocked on https://github.com/ryantm/nixpkgs-update/pull/360, https://github.com/ryantm/nixpkgs-update/pull/361
There isn't any urgency here, we can wait for the PRs to be merged upstream.
=> flake: unpin nixpkgs-update

modules/shared/remote-builder.nix
> [restrict](https://man.openbsd.org/sshd.8#restrict)
Enable all restrictions, i.e. disable port, agent and X11 forwarding, as well as disabling PTY allocation and execution of ~/.ssh/rc. If any future restriction capabilities are added to authorized_keys files, they will be included in this set.
=> modules/shared/remote-builder: use `restrict` for ssh

hosts/web02/secrets.yaml, modules/nixos/monitoring/default.nix
We'd need to do this for loki so we may as well use it for alertmanager as well.
=> modules/nixos/monitoring: put alertmanager behind basic_auth

hosts/build02/nixpkgs-update.nix, hosts/build02/supervisor.py, hosts/build02/supervisor_test.py
Fixes #799.
I went to some lengths to build the entire `build02` machine as a container and run it to make sure that this works, but between not knowing how to stub in my own values for secrets and my suspicion that production `build02` has retained some state that the configuration doesn't create (notably, `/var/cache/nixpkgs-update/fetcher/nixpkgs`), the best I was able to do is verify that this all works once I kick the fetchers manually.
High-level description of changes:
* Created a new service called `nixpkgs-update-supervisor` to replace the named pipe previously used for communication between fetchers and workers. The service implements a priority queue so that no package goes unserviced for too long. The queue is persisted across runs in a SQLite database accessible from …
=> build02/nixpkgs-update: replace fifo with supervisor service

.gitignore
Why
===
* When I entered the directory, a .direnv directory was created and it was not ignored
What changed
===
* Ignore .direnv globally
* Remove now unneeded terraform directory ignore for direnv
=> ignore direnv globally

hosts/build02/nixpkgs-update.nix
This may address the intermittent ConnectionResetErrors we're seeing from the supervisor. By default, socat will terminate its connection to one side half a second after the other side closes; if the supervisor is taking more than half a second to respond, this results in dropped jobs. Bumping this timeout to five seconds should help.
=> build02/nixpkgs-update: make socat more patient

flake.nix
This reverts commit 7f7c0463177c3c8b7ad1c6dfd4c227bb34b750ef.
https://github.com/NixOS/nixpkgs/pull/261159
=> Revert "disable buildbot nixos test for now"

flake.lock, flake.nix
`nixos-unstable-small` moves too fast for darwin systems and devshells.
Could try splitting darwin/linux but I think just using `nixos-unstable` for everything is simpler.
=> flake: nixos-unstable-small -> nixos-unstable

.github/workflows/flake-updates-nixpkgs-update.yml, .github/workflows/flake-updates.yml
The hercules actions won't trigger now that the PR isn't open by a privileged token so we can re-enable automerge.
=> .github/workflows: remove `update-flake-lock` token 

flake.lock, flake.nix
https://github.com/ryantm/nixpkgs-update/pull/370
This has been deploy on build02 for a week.
=> flake: nixpkgs-update: bump 'wait for ofborg' to 60 minutes

flake.nix
Could remove the hercules agent from `darwin02` by using the new `remotePlatformsWithSameFeatures` hercules feature but that would be trading CI performance for admin convenience.
=> flake: cachix-deploy-spec: only deploy darwin03

modules/darwin/community-builder/keys/anthonyroussel, modules/darwin/community-builder/users.nix
Hello!
I [contribute regularly to nixpkgs](https://github.com/NixOS/nixpkgs/pulls?q=is%3Apr+author%3Aanthonyroussel), but I don't own any MacOS workstation to test the builds of the packages I add to nixpkgs.
I would like to use this build box to test that my changes build fine on Darwin, and help improve Darwin support for nixpkgs :)
Is it possible to be added to the darwin build box?
=> modules/darwin/community-builder: add user

.github/workflows/flake-updates.yml, flake.lock, flake.nix
Unpinning `buildbot-nix` so picking up trivial updates is easier but disabling the automerge to ensure changes are reviewed.
=> flake: unpin buildbot-nix

docs/continuous-integration.md
We've run a bunch of builds here and in srvos without any issues so should be fine to advertise this now.
=> docs/continuous-integration: add buildbot

docs/continuous-integration.md, docs/namespace-actions.md, mkdocs.yml
This makes the namespace actions a bit more prominent.
=> doc/continuous-integration: separate namespace actions from self hosted

hosts/build02/nixpkgs-update.nix
This is intended to reduce the impact of incidents like #945.
Reviewing data from the last 23,000+ worker jobs that ran to completion, all but five packages finished in under two hours; the maximum was under eight. So a twelve-hour timeout is a fairly conservative starting point, I think.
=> build02/nixpkgs-update: add timeout for workers

flake.lock, flake.nix, hosts/darwin02/configuration.nix, modules/nixos/monitoring/grafana.nix
Reverts https://github.com/nix-community/infra/pull/893.
Unstable seems to be kind of slow at the moment which makes it a bit inconvenient for us. Can live with the builds for now, might try to switch back in a month or two.
=> flake: nixos-unstable -> nixos-unstable-small

modules/nixos/hydra.nix
Added in b1b2e2c7fe768f924805ede5b2898d1c0779f15e, I don't think this is needed now that the secret isn't accessed via `buildMachinesFiles`.
=> modules/nixos/hydra: remove secret

modules/nixos/buildbot.nix
Buildbot fails if it can't connect to github after the host is rebooted.
=> modules/nixos/buildbot: add `Upholds`

flake.nix
We only need this for the `nixpkgs-update` binary which is cheap for us to build anyway.
Removing this will get rid of a lot of the warnings in the buildbot eval logs.
Before: https://buildbot.nix-community.org/#/builders/6/builds/30/steps/2/logs/stdio
After: https://buildbot.nix-community.org/#/builders/6/builds/33/steps/2/logs/stdio
=> flake: remove nixpkgs-update nixConfig

hosts/build03/configuration.nix, hosts/build03/postgresql.nix, modules/nixos/hydra.nix
Created from https://pgconfigurator.cybertec.at/ with 32gb ram, 8 cores.
We used a version of this for [web01/postgresql](https://github.com/nix-community/infra/blob/bad093e1d9f9c30497c86ed74a92c746c623ad64/hosts/web01/postgresql.nix).
=> build03/postgresql: move from modules/hydra, add config

modules/nixos/hydra.nix
```
error: access to URI ... is forbidden in restricted mode
```
nix 2.19 seems to be broken.
This PR is deployed on build03 with the autoupgrade disabled.
=> modules/nixos/hydra: pin package 

hosts/build02/nixpkgs-update.nix
Haven't tried this for a while, memory needed for evals may still be an issue.
With more projects using buildbot there is less need for another hercules agent. https://github.com/nix-community/infra/pull/990
Each nixpkgs-update worker is throttled to 1 PR an hour so adding another worker won't really make the ofborg situation much worse than it is currently but it will allow nixpkgs-update to process the updates much faster.
=> build02/nixpkgs-update: add another worker

modules/darwin/common/flake-inputs.nix
This was causing unnecessary rebuilds.
=> modules/darwin/common/flake-inputs: fix inputs

modules/nixos/common/security.nix
We only allow publickey auth so this is only of limited value anyway.
It has been disabled for the last couple of months as the nixpkgs module was broken and I forgot to re-enable it.
=> modules/nixos/common/security: drop fail2ban

flake.lock, flake.nix, tasks.py, terraform/shell.nix
We likely won't return to running terraform automatically on CI for a while, if ever.
Don't really need the pin for manual use so we may as well save ourselves an extra input.
=> unpin terraform shell

hosts/build01/configuration.nix, hosts/build02/configuration.nix, hosts/build03/configuration.nix
This was needed for zfs which we aren't using on these hosts.
=> build01,build02,build03: remove hostId

terraform/terraform_cloud.tf
```
╷
│ Warning: Argument is deprecated
│
│   with tfe_workspace.nix-community,
│   on terraform_cloud.tf line 46, in resource "tfe_workspace" "nix-community":
│   46:   execution_mode = "local" # only use it to hold state
│
│ Use resource tfe_workspace_settings to modify the workspace execution settings. This attribute
│ will be removed in a future release of the provider.
│
│ (and one more similar warning elsewhere)
╵
```
=> terraform/terraform_cloud: switch to `tfe_workspace_settings`

modules/nixos/common/default.nix
https://github.com/nix-community/infra/commit/f3967527610aebf42793a6553a73eb8ad5601876
Now we're not using zfs we can go back to using the latest kernel.
=> modules/nixos/common: use latest kernel

modules/nixos/monitoring/prometheus.nix
Having more than two weeks of data is sometimes helpful.
=> modules/nixos/monitoring/prometheus: set retention time to 30 days

modules/darwin/common/reboot.nix, modules/nixos/common/reboot.nix
The original intent was just to make sure that all of the machines didn't reboot at the same time, three hour window will still do that and is a little bit more convenient to monitor.
=> modules/*/reboot: reduce window from 6 to 3 hours

modules/nixos/hydra.nix
Waiting for nix 2.19.3 or 2.20 and for the nixpkgs hydra to be updated to use that version.
=> modules/nixos/hydra: update allowed-uris

modules/darwin/common/default.nix
81dd4e0557c2a5a9e59a3b1546f098044f18b61b
we do the same for nixos
=> modules/darwin/common: only allow ssh_host_ed25519_key

terraform/cloudflare_nix-community_org.tf
This machine (https://github.com/nix-community/darwin-build-box) will be cancelled sometime in the next few weeks.
=> terraform/cloudflare: drop darwin01

hosts/build02/nixpkgs-update.nix
A few times I'll restarted workers that have been stuck for 3+ hours, not much point it letting it run until it hits the 12 hour timeout.
https://github.com/nix-community/infra/pull/951
6 hours seems to cover almost everything, after a couple of weeks we can review the logs, fix/disable problem packages or increase the timeout if necessary?
cc @rhendric
=> build02/nixpkgs-update: reduce timeout to six hours

hosts/build02/nixpkgs-update.nix
Mostly just want to remove cruft, e.g. deleted packages, outdated package sets. I think 18 months is a reasonable window?
cc @rhendric 
Copied service from:
https://github.com/nix-community/infra/blob/6a302a08cb0ffae537caacaa85f89fea9d340bbf/modules/nixos/hydra.nix#L15-L19
=> build02/nixpkgs-update: remove logs older than 18 months

hosts/build02/nixpkgs-update.nix
Spread out new github and repology PRs a little instead of batching them once a day.
I think twice a day should be fine but probably need to check API ratelimits to increase it any further.
cc @rhendric
=> build02/nixpkgs-update: run fetchers every 12 hours

modules/darwin/common/default.nix
We have received a notification from the German Federal Office for Information Security (BSI) about our NetBIOS being enabled, and it potentially being used for DDoS reflection attacks.
=> darwin: disable netbios on activation

hosts/build02/nixpkgs-update.nix
allows us to see how long it runs for and if it ever gets stuck
=> build02/nixpkgs-update: use systemd schedule instead of a sleep

.github/workflows/darwin.yml
add a 15 minute timeout so if the deployment gets stuck it doesn't run until the default 6 hour timeout
=> .github/workflows/darwin.yml: add timeout

modules/nixos/monitoring/prometheus.nix, modules/nixos/monitoring/telegraf.nix
scraping this target with telegraf isn't working since 1.30.0
=> modules/nixos/monitoring: ofborg: telegraf -> prometheus

modules/darwin/community-builder/keys/annalee, modules/darwin/community-builder/users.nix
I'm working on some changes to update darwin bootstrap and being able to test on aarch64 would be helpful.
performing bootstrap builds takes a long time on my hackintosh x64 VM. 6-12 hours so if there is not ample capacity on the machines having access probably won't help.
bootstrap prs:
- https://github.com/NixOS/nixpkgs/pull/295558
- https://github.com/NixOS/nixpkgs/pull/295557
old merge: fixing libcxxabi on clang issues.
- https://github.com/NixOS/nixpkgs/pull/292043
all nixpkgs PRs.
https://github.com/NixOS/nixpkgs/pulls/a-n-n-a-l-e-e
=> darwin/community-builder: add user annalee

modules/nixos/disko-raid.nix
Will switch to xfs on build02 to address the inode problems, would seem to be the simplest option.
- don't really want to go back to zfs and being limited to which kernels we can use. (we also seem to have had high memory usage with zfs.)
- bcachefs is a bit too new. (also disko doesn't have support for bcache multi-disk yet).
- btrfs might be okay but disko doesn't have support for multi-disk yet.
=> modules/nixos/disko-raid: add option for filesystem type

flake.lock, flake.nix
https://github.com/nix-community/infra/issues/1155
Encountered an unexpected macos security issue that blocked access to a new versions of bash, nix and caused the last deployment to fail. Pinning nixpkgs for now while I figure out a proper fix.
=> flake: pin nixpkgs for darwin01 

flake.lock, flake.nix, hosts/build02/nixpkgs-update.nix
Easier to manage these deps in tree than using a nixpkgs checkout on the host.
cc @ryantm
=> build02/nixpkgs-update: update github fetcher 

hosts/build02/gitconfig.txt
`nixpkgs-update` sets https by default but we use ssh.
=> build02/nixpkgs-update/gitconfig: use ssh for push

flake.lock, flake.nix, hosts/build01/configuration.nix, modules/nixos/common/comin.nix, modules/nixos/common/default.nix
Polling the git repo looks much nicer than `autoUpgrade` that we're currently using.
I'd like to trial it on build01 but need to address a couple of thing first.
=> modules/nixos: add comin

hosts/build02/nixpkgs-update.nix
Want to try this for a couple of weeks to see if it helps with some of the nixpkgs-review timeouts and if it can maintain the current pace of updates (currently seems to cycle through everything in a few days.)
=> build02/nixpkgs-update: reduce workers to four

modules/nixos/community-builder/users.nix
i want to do some testing related to untrusted users and distributed builds, and in order to do that i need access to an untrusted user.
=> nixos/community-builder: add binarycat-untrusted user

modules/nixos/monitoring/prometheus.nix, modules/nixos/monitoring/telegraf.nix
This seems to have been fixed upstream, should be in the next release.
https://nixpk.gs/pr-tracker.html?pr=300851
=> Revert "modules/nixos/monitoring: ofborg: telegraf -> prometheus"

flake.lock
This happens quite regularly on dependabot updates and when users do a force push.
=> update buildbot-nix to fix race condition with github's merge ref

flake.lock, hosts/build04/configuration.nix, modules/nixos/common/comin.nix
Will try this for another week or so on two hosts with the prometheus metrics and then look at dropping autoupgrade.
=> modules/nixos/common/comin: add prometheus, build04: switch to comin

modules/nixos/buildbot.nix
This reverts commit 83f3142fd8d08169d0fab4d4a4f83bc603287371.
Seems using this to restart buildbot wasn't a good idea as buildbot may have an actual error.
=> Revert "modules/nixos/buildbot: add `Upholds`"

hosts/build02/nixpkgs-update-backup.nix, hosts/build02/nixpkgs-update.nix
Not sure why these two services have started conflicting recently when they hadn't previously been a problem.
=> build02/nixpkgs-update: delete old logs daily, run backup after delete

hosts/build02/configuration.nix
By default it can use up to 64GB (50%) so limiting it to 16GB seems like it might help?
___
=> build02: set zfs_arc_max

modules/darwin/common/default.nix
Each time we've set up a new darwin machine I've run these manually and then forgotten to add them here.
=> modules/darwin/common: add mdutil to postActivation script

modules/nixos/monitoring/alert-rules.nix
seems 30m isn't quite long enough for the gandi vm, I'll bump this to 90m so it'll only fire if there is an actual issue.
=> modules/nixos/monitoring/alert-rules: increase comin commit alert to 90m

modules/nixos/buildbot.nix
Buildbot fails if it can't connect to github after the host is rebooted.
alternative to 83f3142fd8d08169d0fab4d4a4f83bc603287371
=> modules/nixos/buildbot: set Restart, RestartSec

docs/update-bot.md, hosts/build02/nixpkgs-update.nix, modules/nixos/monitoring/telegraf.nix, terraform/cloudflare_nix-community_org.tf
@nix-community/admin Are we okay with the logs on their own subdomain? Simpler for future redirects if nixpkgs-update does move to the nixos org.
=> serve logs on nixpkgs-update-logs.nix-community.org

hosts/build02/configuration.nix, hosts/build02/nixpkgs-update.nix
The bot seems to be falling behind a little now with just four workers so adding another one back. 
Also going to try giving zfs a little bit more memory as recently we haven't had any crashes and only a couple of OOMs.
=> build02: bump zfs_arc_max to 24GB, build02/nixpkgs-update: add another worker

hosts/build02/nixpkgs-update.nix
cc @ryantm @rhendric
I've tested the change in this PR and it seems to be fine. The workers can access the github API (to open PRs and check for open PRs) and the delete-done service for merged PRs branches also works.
The `/var/lib/nixpkgs-update/worker/github_token.txt` symlink was added in https://github.com/nix-community/infra/commit/37b2fbef9070024aad43ce1535dcb8644087c96f as part of the change to the worker model.
After the initial change this code was touched in https://github.com/nix-community/infra/commit/8918a47f7e0cd88c359977d507e2bf59039c756d, https://github.com/nix-community/infra/commit/6843ef7472b9d1ef6d2faee00403d39d5c0bfabe, https://github.com/nix-community/infra/commit/399db233f24edcea64979adc82e22a5ab80c4fe8.
=> build02/nixpkgs-update: remove extra github_token symlink

modules/darwin/hercules-ci/default.nix
This reverts commit 5da85a9b7276f15a64052dcc820ab210d742b914.
Fixed in nix-darwin by https://github.com/LnL7/nix-darwin/commit/251eaabfa0f421a864e75e6b1a23c2c73e7bc332
=> Revert "modules/darwin/hercules-ci: add security to service path"

modules/darwin/community-builder/default.nix, modules/nixos/community-builder/default.nix
Biggest benefits are better prompt and the ability to properly use arrow up
to go through the history
`nix<up>` searches through commands which start with `nix`
https://grml.org/
I like using this as the the default configuration on all my machines
=> darwin & linux community builder: add a sane zsh config

default.nix, flake.lock, flake.nix
It's easier to be able to fall back to the old cli sometimes.
I'm fine with not adding it if anyone is 👎 .
cc @nix-community/admin
=> flake: add nix-community/flake-compat

modules/darwin/hercules-ci/default.nix
This reverts commit 1f6af7ef7557dc4c4853021fb4664a886e4b2701.
=> Revert "modules/darwin/hercules-ci: add sandbox workaround"

flake.lock, flake.nix
Eventually I'll finish fixing the haskell breakage in https://github.com/nix-community/nixpkgs-update/pull/419 but for now I'll go back to following nixpkgs for these deps.
=> flake: nixpkgs-update: follow nixpkgs for runtime deps

terraform/hydra-projects.tf
I don't know how much resources that would take, but we could give it a go.
CUDA packages are slow to build, and not cached by upstream due to upstream not building unfree packages. This could help the team quite a bit.
=> hydra: build CUDA packages for the CUDA team

hosts/build02/nixpkgs-update.nix
This reverts commit 6991dc3f4bdf8e2b1ab3d192ec0a4d98949ac004.
ofborg seems worse the last couple of weeks
=> Revert "build02/nixpkgs-update: add another worker"

hosts/build01/configuration.nix, hosts/build02/configuration.nix, hosts/build03/configuration.nix, modules/nixos/disko-zfs.nix
I think this is okay to use by default? Only host that isn't currently using it is build04.
=> use zpool workaround by default

modules/nixos/common/default.nix, modules/shared/nix-daemon.nix
Not sure that optimising the entire store on a schedule is better than `auto-optimise-store` on most full multi TB disks so just disable it for now and keep the status quo.
=> modules/nixos/common: disable scheduled optimise

modules/nixos/monitoring/prometheus.nix
Every 4 hours is a bit spammy.
=> modules/nixos/monitoring/prometheus: increase repeat_interval to 12h

hosts/build04/configuration.nix
```
MaxStartups
Specifies the maximum number of concurrent
unauthenticated connections to the SSH daemon.
Additional connections will be dropped until
authentication succeeds or the LoginGraceTime expires for
a connection.  The default is 10:30:100.
Alternatively, random early drop can be enabled by
specifying the three colon separated values
start:rate:full (e.g. "10:30:60").  sshd(8) will refuse
connection attempts with a probability of rate/100 (30%)
if there are currently start (10) unauthenticated
connections.  The probability increases linearly and all
connection attempts are refused if the number of
unauthenticated connections reaches full (60).
```
=> build04: set ssh MaxStartups

flake.lock, flake.nix, hosts/build01/default.nix, hosts/build02/default.nix, hosts/build03/default.nix, hosts/build04/default.nix, hosts/darwin01/default.nix, hosts/darwin02/default.nix, hosts/web02/default.nix
There are a couple of other host config flake-parts modules but IMO this one is "lite", it saves some boilerplate without needing to rearchitect the entire repo and if necessary it can be removed fairly easily.
=> flake: add lite-config

modules/nixos/buildbot.nix
This hasn't been very useful so dropping it, might revisit after we eventually move everything on to buildbot.
=> modules/nixos/buildbot: remove metrics

docs/cache.md, docs/continuous-integration.md, docs/package-sets.md, mkdocs.yml
May as well advertise this, it is stable enough that we shouldn't have to disable it again.
=> docs: add cache, package-sets

modules/nixos/common/comin.nix, modules/nixos/monitoring/alert-rules.nix
https://github.com/nix-community/infra/commit/0a17c87a4f1cdafa7a0fe0a4a0a0b28b6bccbf0e reports which flake path each host is currently on so the comin monitoring isn't as useful.
=> comin: remove promethueus, alert rules

.github/workflows/flake-updates.yml, .github/workflows/repo-list.yml
Don't really need automerge for a couple of PRs and sometimes I'd rather review flake updates changes before they are merged.
=> .github/workflows: remove automerge

flake.lock, flake.nix, modules/nixos/hydra.nix
Manually deployed on build03 for testing.
=> hydra: switch to fork

modules/shared/telegraf.nix
seems nix flake metadata breaks running as telegraf user with nix 2.24
=> modules/shared/telegraf: fix host info script

flake.nix
Makes the buildbot output a bit easier to read.
=> flake: use host prefix for darwin and nixos configuations

modules/nixos/hydra.nix
This reverts commit 5f62fc66cb735950c9f1431d37dfd8e940e23a76.
Fixed in nixpkgs.
=> Revert "modules/nixos/hydra: fix hydra-compress-logs"

terraform/hydra-projects.tf
CUDA is one of the more costly ecosystems for users to build, so providing a cache for NixOS stable would be very much appreciated.
=> terraform/hydra-projects: add cuda-stable

modules/darwin/community-builder/default.nix, modules/nixos/community-builder/default.nix, modules/shared/community-builder.nix, modules/shared/nixpkgs-clone.bash
Closes https://github.com/nix-community/infra/issues/1453
=> modules/community-builder: add nixpkgs clone

modules/shared/community-builder.nix
For easier monitoring of system resources I propose to add [btop](https://github.com/aristocratos/btop) and `htop` to the community builders packages.
=> community-builder: add btop, htop to systemPackages

modules/nixos/buildbot.nix
This had been broken but was fixed in buildbot 4.0.3.
=> modules/nixos/buildbot: add title, titleUrl

modules/darwin/community-builder/default.nix, modules/nixos/community-builder/default.nix, modules/shared/community-builder.nix
Will probably keep this here rather than making a shared terminfo module in srvos as there would also need to handle cross.
=> modules/shared/community-builder: add terminfo packages

modules/nixos/monitoring/alert-rules.nix
no point in keeping this when ofborg is in such a bad state that it fires continuously
=> modules/nixos/monitoring/alert-rules: remove OfBorgEvalQueue

modules/nixos/builder.nix
https://lore.kernel.org/io-uring/25c4c665-1a33-456c-93c7-8b7b56c0e6db@kernel.dk/T/#t
This patch is queued for 6.6.
=> modules/nixos/builder: add io_uring kernel patch

modules/nixos/monitoring/hosts.nix, modules/nixos/monitoring/prometheus.nix, modules/nixos/monitoring/telegraf.nix
Rather than using another list of hosts we can reuse known hosts.
=> modules/nixos/monitoring: import hosts from knownHosts

flake.nix, modules/default.nix
@zimbatm Do you mind if we reuse this code from `blueprint`?
=> flake: expose {darwin,nixos}Modules automatically

modules/shared/nix-daemon.nix
We actually only want this on the CI hosts, not nixpkgs-update or the community builders.
=> Revert "modules/shared/nix-daemon: set max-silent-time, timeout"

terraform/hydra-nixpkgs.tf
https://hydra.nix-community.org/jobset/nixpkgs/cuda-stable
https://hydra.nix-community.org/jobset/nixpkgs/cuda-stable-previous
cc @zimbatm @SomeoneSerge @mweinelt
=> terraform/hydra-nixpkgs: cuda-stable: 24.05 -> 24.11

modules/darwin/community-builder/users.nix, modules/nixos/community-builder/users.nix
Interesting failure with nushell :thinking: 
```
cannot build on 'ssh://mrcjkb@darwin-build-box.nix-community.org': error: cannot connect to 'mrcjkb@darwin-build-box.nix-community.org': Error: nu::shell::external_command
× External command failed
╭─[source:1:1]
1 │ nix-store --serve --write
· ────┬────
·     ╰── Command `nix-store` not found
╰────
help: Did you mean `history`?
```
=> users/mrcjkb: set default shell to zsh

docs/monitoring.md, modules/nixos/monitoring/default.nix, modules/nixos/monitoring/grafana.nix, modules/nixos/monitoring/oauth2-proxy.nix, modules/nixos/monitoring/prometheus.nix, secrets.yaml, secrets/nginx-basic-auth-file.age, secrets/oauth2-proxy-key-file.age, secrets/secrets.nix, terraform/cloudflare_nix-community_org.tf
reverts d4343f7ebe1f14e336fca4520b32ede7dfac3d8d
Going back to separate subdomains as I'd like to put alertmanager behind oauth2 proxy and it is simpler to only need to include the alertmanager subdomain.
This is already deployed onto web02.
=> modules/nixos/monitoring: switch back to separate subdomains, oauth-proxy for alertmanager

docs/update-bot.md, hosts/build02/nixpkgs-update.nix, hosts/build02/update_queue.py
> it is technically possible for you to download the supervisor SQLite state database from https://nixpkgs-update-logs.nix-community.org/~supervisor/state.db and issue the appropriate queries against it (after having studied https://github.com/nix-community/infra/blob/master/hosts/build02/supervisor.py to understand the queue schema). But it's not exactly end-user friendly at the moment. (Some day I may publish a dashboard.)
@rhendric I thought I'd throw together something basic so people don't need to play around with the database. I'm fine with replacing this with your dashboard, if you do make one.
https://nixpkgs-update-logs.nix-community.org/~supervisor/queue.html
=> nixpkgs-update: add queue

hosts/build02/filter.sed, hosts/build02/nixpkgs-update.nix, hosts/build02/repology.bash
Closes https://github.com/nix-community/infra/issues/1192
Currently repology upstream is being rewritten in rust so I for now just going to use bash/jq, can look at rewriting it in python or rust once repology is stable.
Adding an update filter as lets the bot update packages that would otherwise create multiple PRs for the same update and also reduce time spent working on updates that don't work.
=> nixpkgs-update: add fetch-repology script, filter updates

modules/nixos/common/builder.nix
zfs 2.2.7 added support for 6.12 kernel.
=> modules/nixos/common/builder: switch to 6.12 kernel

hosts/build01/default.nix
@Mic92 Do we need to make any changes for Direct I/O, looks like it is enabled by default?
=> build01: switch to zfs_unstable

dev/packages.nix, dev/shell.nix, dev/sk-libfido2.patch, flake.nix, modules/darwin/community-builder/default.nix
With macos 13 and older it seems we would have needed to replace the native sshd to support security keys, since macos 14 sshd has support for security keys but requires the fido lib.
Not tested but it should work.
=> modules/darwin/community-builder: add SecurityKeyProvider

modules/nixos/common/update.bash, modules/nixos/common/update.nix
This reverts commit 01137d599d5bccdb0f3399d51930534f0a7c05c3.
I noticed that this breaks the disko installTest so probably want to find any way to do this.
=> Revert "modules/nixos/common/update: use grub.extraInstallCommands for boot diff"

hosts/build02/filter.sed
There are now multiple beam package sets, so let's limit to updating one.
=> nixpkgs-update: filter beam package set to a single set

tasks.py
this is faster but it assumes that the flake inputs can be substituted on the target
=> tasks.py: use copy instead of archive for deploy

modules/nixos/monitoring/alert-rules.nix
https://github.com/nix-community/infra/issues/1644
=> modules/nixos/monitoring/alert-rules: disable smart warnings on build05

modules/nixos/common/default.nix, modules/nixos/common/update.bash, modules/nixos/common/update.nix
Second attempt at adding a boot diff (https://github.com/nix-community/infra/pull/1609) but using preSwitchChecks (https://github.com/NixOS/nixpkgs/commit/6e192c4489ea44c48876faa11060798fb9502146) which works for boot/switch, grub/systemd-boot and has an escape hatch which can be used for things like disko install tests, nixos-anywhere, etc.
I've move this to srvos after we've tested it here for a bit.
=> modules/nixos/common: use preSwitchChecks for update diff

hosts/build03/default.nix, modules/nixos/common/builder.nix
Not completely sure it is the kernel but aarch64-linux seems to be worse the last couple of weeks, crashing or freezing.
=> modules/nixos/common/builder: switch back to 6.6 kernel

modules/nixos/community-builder/keys/misuzu, modules/nixos/community-builder/users.nix
I've [used](https://github.com/NixOS/aarch64-build-box/blob/05298da5e1c3bed11448241134e0f1e8bcef0a1e/users.nix#L371) https://github.com/NixOS/aarch64-build-box before, but it's gone now and testing big packages on my rpi4 is a pain...
=> nixos/community-builder: add misuzu

tasks.py
Switched to copy in https://github.com/nix-community/infra/pull/1640 but archive it still useful sometimes.
=> tasks.py: use archive for deploy when the flake has file or path inputs

modules/nixos/hercules-ci.nix
Takes 90 seconds to timeout before being killed. Only happens intermittently.  
```
Jan 22 05:04:56 build03 systemd[1]: Stopping hercules-ci-agent.service...
Jan 22 05:06:26 build03 systemd[1]: hercules-ci-agent.service: State 'stop-sigterm' timed out. Killing.
Jan 22 05:06:26 build03 systemd[1]: hercules-ci-agent.service: Killing process 51552 (hercules-ci-age) with signal SIGKILL.
Jan 22 05:06:26 build03 systemd[1]: hercules-ci-agent.service: Killing process 51571 (hercules-ci-age) with signal SIGKILL.
Jan 22 05:06:26 build03 systemd[1]: hercules-ci-agent.service: Killing process 1935631 (ghc_worker) with signal SIGKILL.
Jan 22 05:06:26 build03 systemd[1]: hercules-ci-agent.service: Killing process 1937690 (n/a) with signal SIGKILL.
Jan 22 05:06:26 build03 systemd[1]: …
```
=> modules/nixos/hercules-ci: set TimeoutStopSec

modules/nixos/common/default.nix
Try to avoid having stuck machines that need to have their power cycled manually.
=> modules/nixos/common: reboot on panic

modules/nixos/common/default.nix
A stuck hydra build can trigger this which can then cause a loop as the hydra build is restarted.
Probably useful to monitor hung tasks, I'll look into that.
=> modules/nixos/common: remove hung_task_panic

dev/docs.nix, docs/community-builders.md, docs/continuous-integration.md, docs/infrastructure.md, flake.nix, mkdocs.yml
Lets users see all of the features and platforms of the hosts in one place.
=> docs/infrastructure: embed host config json

modules/nixos/community-builder/keys/booxter, modules/nixos/community-builder/users.nix
I already had access to darwin builder; I now need nixos because my
machine is not capable enough to survive a firefox build anymore.
=> nixos/community-builder: add booxter

flake.lock, flake.nix, modules/nixos/cgroups.nix
Removing this as it was never really used and the telegraf cgroup plugin will have better support for v2 cgroups in the next version (1.34.0) that we cloud use instead.
=> modules/nixos: remove cgroup-exporter

modules/nixos/common/builder.nix
https://github.com/nix-community/infra/issues/1619
```
[zowoq@build04:~]$ ras-mc-ctl --status
ras-mc-ctl: drivers not loaded.
```
The current version in nixpkgs is a year old, I'll wait for the newer version in https://nixpkgs-tracker.ocfox.me/?pr=369375 to land.
=> modules/nixos/common/builder: add rasdaemon

hosts/build02/nixpkgs-update.nix, hosts/build02/packages-with-update-script.nix
=> nixpkgs-update: use nixos-unstable instead of master for updateScript fetcher, run github fetcher every 6 hours

modules/nixos/community-builder/keys/grimmauld, modules/nixos/community-builder/users.nix
I am active building AppArmor support for NixOS, and libapparmor changes cause a mass rebuild which makes testing on my personal laptop not exactly viable.
I also recently started looking into deprecating SDL1 (for SDL12_compat), which also causes mass rebuilds.
Most recently, i wanted to experiment with custom compiles of firefox, including updating LibreWolf to the most recent version, but compiling firefox is too big a compile task.
I already had a chat with people from the community a while ago (emily and hexa, i think? i don't quite remember), and got the suggestion to sign up for community builders.
I declined at the time, referring to other IRL obligations currently taking up my time. However, i have now decided having the access can't hurt, and will be useful. Especially …
=> modules/community-builder: add grimmauld

dev/packages.nix
> https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v5.0.0
> v5.x of this provider is a ground-up rewrite of the SDK, using code generation from our OpenAPI spec.
5.0.0 and 5.1.0 were basically broken, 5.2.0 still seems to have problems, would need to either drop and reimport most of the cloudflare config or perform similar steps on the terraform state file, for now I think pinning the provider to v4 is the easier option.
=> dev/packages: pin cloudflare provider to v4

flake.lock, flake.nix, modules/nixos/cgroups.nix
Switching to the maintenance branch for various fixes not yet tagged, will look at switching to a newer version of nix once the nix packaging in nixpkgs for 25.05 is sorted.
=> use 2.25-maintenance branch for nix_2_25

modules/nixos/monitoring/alert-rules.nix
RAS has 17 different metrics, for now probably simplest to just check for non-zero values.
Closes https://github.com/nix-community/infra/issues/1619
=> modules/nixos/monitoring/alert-rules: add rasdaemon

dev/packages.nix
Seems something in 3.2 or 3.3 is changed or broken, this alert start firing for build05 but it is already disabled.
https://github.com/nix-community/infra/blob/b8130c72a8a66156867d3e3245225083a68c89ae/modules/nixos/monitoring/alert-rules.nix#L52
=> dev/packages: pin prometheus

modules/nixos/hydra.nix
The comment says sha1, but hydra can deal with argon2id hashes just fine. Wondering what, if anything, creates that limitation.
The `hydra-create-user` script even has instructions how to generate such a hash.
```
Hydra uses Argon2id hashes, which can be generated like so:
$ nix-shell -p libargon2
[nix-shell]$ tr -d \\n | argon2 "$(LC_ALL=C tr -dc '[:alnum:]' < /dev/urandom | head -c16)" -id -t 3 -k 262144 -p 1 -l 16 -e
foobar
Ctrl^D
$argon2id$v=19$m=262144,t=3,p=1$NFU1QXJRNnc4V1BhQ0NJQg$6GHqjqv5cNDDwZqrqUD0zQ
```
=> modules/nixos/hydra: create account for hexa

flake.lock, flake.nix
=> flake: switch to shallow nixpkgs clone

flake.lock, flake.nix, hosts/build01/default.nix, hosts/freebsd/configuration.nix, hosts/freebsd/ssh.nix, hosts/freebsd/telegraf-config.nix, hosts/freebsd/telegraf-service.nix, modules/nixos/freebsd-builder.nix, modules/nixos/monitoring/prometheus.nix, modules/shared/host-info.bash, modules/shared/telegraf.nix
- ~~currently can't build anything in the vm~~:
-  ~~`
error: build of '/nix/store/hicd8c5cnfnzc91kjqfhwdrc2d99n9mq-bootstrap-archive.drv' on 'ssh-ng://nix@freebsd-builder' failed: error: Failed to mount nullfs for /nix/store/hicd8c5cnfnzc91kjqfhwdrc2d99n9mq-bootstrap-archive.drv.chroot/bin/sh - Invalid fstype: Invalid argument
`~~
- ~~`error: builder for '/nix/store/*.drv' failed due to signal 11 (Segmentation fault)`~~
- ~~initialHashedPassword~~
- Won't bother with this or putting ssh keys in sops for now. Neither of the VMs are directly exposed, on build01 (build box) it doesn't really matter if we allow everyone with ssh access to the machine to also have root in the VM and on build03 (CI) only the community admins have ssh access to the machine anyway.
- ~~telegraf: `ld-elf.so.1: …
=> nixbsd freebsd builder

modules/darwin/community-builder/users.nix, modules/nixos/community-builder/users.nix
Currently the nix-community admins share the admin account on the darwin boxes, for now I'll just manage the sudo permissions manually for other users.
=> modules/nixos/community-builder/users: allow wheel group

hosts/build02/default.nix, modules/shared/ci-builder.nix
OOMs and lockups are intermittent problems on these hosts, don't really want to limit max-jobs as I think may cause more problems and also can't really reduce max-jobs any more for hydra anyway. Will try this for a couple of weeks, I'm hoping it'll be an overall improvement.
=> build02, modules/shared/ci-builder: limit cores

modules/nixos/monitoring/alert-rules.nix
=> modules/nixos/monitoring/alert-rules: silence vm reboot

.sops.yaml, dev/sops.nix, flake.lock, flake.nix, hosts/build03/default.nix, hosts/build03/secrets.yaml, modules/nixos/rfc39.bash, modules/nixos/rfc39.nix, modules/secrets/rfc39_private_key.der, sops.nix, tasks.py
=> build03: add rfc39

docs/continuous-integration.md, flake.lock, modules/nixos/buildbot.nix, terraform/github-repo-infra.tf
=> modules/nixos/buildbot: disable topic, switch to repoAllowlist

dev/packages.nix, flake.lock, flake.nix
Follow upstream for now while it is active and we're trying the new queue runner, will also allow us to get the security fixes as soon as they are released.
https://discourse.nixos.org/t/pre-disclosure-announcement-security-advisory-for-hydra-on-august-12-2025/67615
=> switch to hydra upstream package

modules/nixos/common/armv7l.nix
Otherwise the following:
```
ssh aarch64-build-box.nix-community.org nix build nixpkgs#legacyPackages.armv7l-linux.hello
```
Fails with:
```
error: a 'armv7l-linux' with features {gccarch-armv7-a} is required to build '/nix/store/j7d3qk6a5s5lj7apn9pja6rhixahlnyr-bootstrap-stage0-glibc-bootstrapFiles.drv', but I am a 'aarch64-linux' with features {benchmark, big-parallel, gccarch-armv8-a, kvm, nixos-test, uid-range}
```
=> armv7l: Add also a proper system feature

hydra/armv7l-linux.nix, terraform/hydra-nixpkgs.tf
https://hydra.nix-community.org/jobset/nixpkgs/armv7l-linux
For now this will just keep the stdenv cached, once cache issues are addressed (https://github.com/nix-community/infra/issues/1926) we can look at building more.
=> terraform/hydra-nixpkgs: add armv7l-linux

modules/nixos/disko-zfs.nix
Won't reprovision the machines, I'll just create the dataset manually.
`zfs create -u -o sync=disabled -o mountpoint=legacy zroot/tmp`
cc @Mic92
=> modules/nixos/disko-zfs: add dataset for /tmp

hosts/build02/nixpkgs-update.nix
This reverts commit b90a577268bc6382cf84c997cba8f94ec7c9451d.
seems to be fixed in 3.5.0
=> Revert "nixpkgs-update: pin nixpkgs-review"

flake.lock, modules/darwin/common/default.nix, modules/nixos/common/default.nix, modules/nixos/disko-zfs.nix
Did this for /tmp in https://github.com/nix-community/infra/pull/1942.
Won't reprovision the machines, I'll just create the dataset manually.
`zfs create -u -o sync=disabled -o mountpoint=legacy zroot/build`
cc @Mic92
=> modules/nixos/disko-zfs: add dataset for /nix/var/nix/builds

flake.nix, hosts/build01/default.nix, hosts/build03/default.nix, modules/nixos/hydra.nix, modules/nixos/monitoring/prometheus.nix
@rhelmot I've seen you comment that you have other commitments and won't be working on this for a while. The freebsd stdenv in nixpkgs has been broken for a while now, I've looked at fixing it but really requires someone with more knowledge of bsd and stdenv to fix it and keep it working. For now I'm going to disable the bsd VMs and the native CI jobs but I'll leave cross jobset for the nixbsd flake enabled. I'm happy to re-enable it for you or anyone else that will make use of it.
=> disable bsd VMs
