nix-community/infra

users/worldofpeace.nix
Thanks for the nudge @adisbladis :grapes:
=> users: add worldofpeace

build01/nixpkgs-update.nix, nix/sources.json
With these changes nixpkgs-update should run daily automatically!
=> [nixpkgs-update] automatically run

.github/workflows/nix.yml, default.nix, deploy, nix/default.nix, nix/overlay.nix, profiles/common.nix, shell.nix
pre-build the machines so they can be pulled from the cache
=> ci: add basic nix and cachix support

nix/sources.json
- move usage documentation into its own document (timokau/marvin-mk2#17)
- react to commands in reviews (timokau/marvin-mk2#18)
- automatically set to `needs_work` on change requests (timokau/marvin-mk2#18)
- automatically set `needs_merge` -> `needs_review` on pushes (timokau/marvin-mk2#19)
=> marvin: update

build01/hydra.nix
Hydra was not responding anymore...
=> hydra: increase Postgresql cache size

build01/configuration.nix
=> setup automatic garbage collection

build01/hydra-declarative-projects.nix
https://git.sr.ht/~ehmry/genodepkgs/tree/master/hydra.json
=> hydra: add Genodepkgs project

README.md, users/mic92.nix
to set up:
- monitoring (logs to IRC)
- continuous deployment to build01/build02 with drone
=> add mic92 as admin

build01/configuration.nix, build02/configuration.nix, profiles/common.nix, profiles/users.nix
Untested, lets see if it evaluates.
=> move users configuration to seperate profile

nix/overlays.nix, nix/sources.json, shell.nix
This reverts commit 49e9068bd0e5d9888d89d93b5c13def25fd513b4.
=> Revert "remove broken niv"

build01/configuration.nix, services/marvin-mk2.nix, terraform/cloudflare_nix-community_org.tf
Add a layer of indirection to make the migration to build03 easier.
Please update the GitHub Webhook to point to this address first.
/cc @timokau @Mic92
part of #85
=> marvin-2k: add marvin-2k.nix-community.org

.envrc, README.md, deploy, deployment.nix, nix/overlays.nix, nix/sources.json, shell.nix
nixops is broken and requires a pinned channel.
For our use case morph seems simpler as it is stateless
=> switch from nixops to morph

nix/sources.json
https://github.com/NixOS/nixpkgs/pull/147834
=> incorperate acme fix

roles/builder/keys/ckie, roles/builder/users.nix
*(No fancy formatting today, this is just the commit message)*
I maintain nix-doom-emacs: https://github.com/nix-community/nix-doom-emacs
and I currently have a PR that I can't really build locally due to the
~~20~~ 48 rebuilds: https://github.com/NixOS/nixpkgs/pull/158778
https://matrix.to/#/!KqkRjyTEzAGRiZFBYT:nixos.org/$qKKGPfDiNT3Ty8MxTLBg3fgugBfDjkMONnYxWKgQ6x0?via=nixos.org&via=matrix.org&via=tchncs.de
=> builder/users: add ckie

flake.lock, flake.nix
merged into upstream
fixes CI https://github.com/nix-community/infra/runs/6051504935
=> flake: drop workaround branch

flake.nix
Done with the edit button; hope I got it right.
=> flake.nix: Use mkFlake convenience

services/hydra/default.nix
Fixes eval failure in https://github.com/nix-community/infra/pull/263.
=> hydra: fix eval

terraform/hydra-projects.tf
=> hydra-projects.tf: increase Kittybox check_interval to 1800

flake.lock, flake.nix, roles/aarch64-builder.nix, services/hydra/default.nix
=> fix hydra instead of using local builder via ssh

flake.lock, flake.nix
=> flake: switch back to NixOS/hydra

flake.lock, flake.nix
=> flake: switch hydra nixpkgs follow to stable channel

flake.nix
=> flake: fix duplicate/missing system

flake.lock, flake.nix
=> flake: update flake-parts follows

roles/security.nix
=> add aarch64-nixos-community to knownHosts

services/hydra/default.nix, tasks.py
=> hydra: switch to buildMachinesFiles

build03/configuration.nix, flake.lock, flake.nix, services/hydra/default.nix
Seems like this works, at least for now.
~~`hydra` was just bumped in nixpkgs, need to wait for it to land in unstable-small.~~
=> switch to nixpkgs hydra

flake.lock, flake.nix, shell.nix
~~Need to wait for https://github.com/NixOS/nixpkgs/pull/199257 to land in nixos-unstable-small.~~
=> switch to nixpkgs deploykit

.mergify.yml
=> mergify: rebase merge

terraform/cloudflare_nix-community_org.tf, terraform/hydra-projects.tf, terraform/main.tf
=> terraform cleanups

shell.nix
=> shell.nix: various

roles/nix-daemon.nix
follow up from bfaa5025234a3ed32bc3ae494ea0f2df78b9d2a0
=> export flake information into monitoring

.github/labeler.yml, .github/workflows/labels.yml, .github/workflows/terraform.yml, .sops.yaml, bors.toml, terraform/.envrc, terraform/deploy, terraform/secrets.yaml
cc @Mic92 @zimbatm 
Opened this for comment but TBH it's probably not worth merging here as mergify is more useful as terraform changes don't happen very often. However I think this workflow would work well for managing the nixos.org hydra.
The atlantis package that I mentioned on matrix isn't actually suitable for use in public repos, there are a few alternatives but they are either fairly new, not compatible with our terraform packaging, targeting enterprise ($$$), etc.
=> add terraform deploy action

services/hound/hound.json
=> hound: update

roles/auto-upgrade.nix, roles/common.nix
=> common: remove haveged, autoUpgrade: add accept-flake-config flag 

build02/nixpkgs-update.nix, roles/common.nix, roles/zfs.nix
=> various cleanups

README.md, services/hound/README.md
It's a bit annoying trying to keep hard wrap consistent and github markdown seems to ignore it anyway.
=> docs: soft wrap

terraform/cloudflare_nix-community_org.tf
=> terraform/cloudflare: add dns for nur-update

shell.nix
=> shell: use toString for sopsPGPKeyDirs

build04/configuration.nix, roles/remote-builder/aarch64-build04.nix
=> build04: disable default system-features

.github/workflows/terraform.yml
=> .github/workflows/terraform.yml: add accept-flake-config

build04/configuration.nix, flake.nix
Fix eval error: https://hercules-ci.com/github/nix-community/infra/jobs/667
=> flake: remove build04

ci.nix, roles/hercules-ci/default.nix, roles/security.nix, services/hydra/default.nix, users/lib.nix
=> apply statix simplication

build02/configuration.nix, roles/common.nix
=> build02: reenable hercules, roles/common: enabled zramSwap 

build01/configuration.nix, roles/remote-builder/aarch64-build04.nix, roles/remote-builder/aarch64-nixos-community.nix
=> misc cleanups

build01/configuration.nix
=> build01: emulate riscv64

build04/configuration.nix, roles/remote-builder/aarch64-build04.nix
=> build04: reenable big-parallel

README.md, docs/README.md
=> docs/README.md: reorganise

treefmt.nix
This is very tedious to have as a CI check.
=> treefmt: remove deadnix

HOSTS.md, deploy, inv, tasks.py
=> deploy -> inv, tasks.py: add .ruff_cache, result* to excludes 

terraform/cloudflare_nix-community_org.tf
https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/verifying-your-custom-domain-for-github-pages#verifying-a-domain-for-your-organization-site
=> terraform/cloudflare: add nix-community.org verification for github

.github/settings.yml
self-configure using the settings app.
Fixes #374
=> github: introduce settings app

services/hound/hound.json, services/hound/update-hound.py, tasks.py
=> hound: various

.github/settings.yml, flake.lock, flake.nix
=> drop unused mmdoc

.github/settings.yml, roles/builder/packages.nix
=> .github/settings.yml: remove moderator team, roles/builder/packages: various

.github/settings.yml
=> .github/settings.yml: fix mergify

roles/builder/packages.nix
=> roles/builder/packages: reenable kitty terminfo

README.md
=> README.md: admin team responsibilities and quorum

shell.nix, terraform/main.tf, terraform/secrets.yaml, terraform/terraform_cloud.tf
> Please don't merge this yet. This needs to be coordinated to import all the terraform state of the existing resources before. 
Continuing on the road of consolidation and transparency. This maps the current resources that we have.
**Status:** open for review
=> terraform: configure terraform cloud

terraform/terraform_cloud.tf
=> terraform: invite admins to terraform cloud

README.md, docs/README.md
=> docs: list all the support options

terraform/terraform_cloud.tf
=> terraform cloud: add the missing admins

.github/workflows/flake-updates.yml
=> switch to github bot for flake updates

terraform/cloudflare.tf, terraform/cloudflare_nix-community_org.tf, terraform/main.tf, terraform/terraform_backend.tf, terraform/terraform_providers.tf
Misc cleanup that accumulate over time
- terraform: remove deprecated cloudflare account_id argument
- terraform: clean nix-community.org code
- terraform: remove main
=> terraform cleanup

docs/README.md
=> docs/README.md: update sponsors

terraform/cloudflare_nix-community_org.tf
@ehmry is the server still active?
=> Remove mumble

.github/workflows/terraform.yml, shell.nix, terraform/terraform, terraform/terraform_providers.tf
=> terraform: use sops provider, drop wrapper

.sops.yaml, shell.nix, tasks.py
=> tasks.py: add ssh-to-age to shell and update comments

flake.lock, shell.nix, terraform/gandi.tf, terraform/secrets.yaml, terraform/terraform_providers.tf
=> use gandi for our domains

.github/labeler.yml
useful to see if these files are touched to avoid merge conflicts
=> .github/labeler.yml: add `sops secrets` label

docs/README.md
Provide a better Gandi logo :)
=> docs: update Gandi logo

ci.nix, shell.nix, terraform/flake.lock, terraform/flake.nix
=> terraform: pin terraform and providers in separate flake

.sops.yaml, build04/configuration.nix, build04/hardware-configuration.nix, roles/hercules-ci/secrets.yaml, roles/nix-community-cache/secrets.yaml, terraform/.envrc, terraform/cloudflare_nix-community_org.tf
=> build04: rebuild machine

.gitignore
=> gitignore .direnv in terraform dir

roles/security.nix
follow up from dfc0db1caf4db2fbaf7091c59e5f7306213f1119
=> roles/security: update build04

flake.lock, flake.nix
=> flake: update srvos

tasks.py
=> change deployment to use flake only

.github/workflows/hound.yml, services/hound/hound.json, services/hound/update-hound.py
=> add update hound action

ci.nix
=> ci: inherit lib from nixpkgs

.github/labeler.yml
=> .github/labeler.yml: update sops labels

.sops.yaml, roles/hercules-ci/default.nix, roles/hercules-ci/secrets.yaml, terraform/secrets.yaml
Needs to be deployed on the machines first for https://github.com/nix-community/infra/pull/468.
=> allow hercules to access terraform secrets

.github/workflows/hound.yml
=> .github/workflows/hound.yml: various

README.md, docs/README.md
cc @nix-community/infra
- sort by priority: urgent, general, casual
- use issues for urgent matters, otherwise use discussions
=> docs: various

tasks.py, terraform/flake.lock
```
Terraform updates:
terraform: 1.3.9 → 1.4.0
terraform-provider-cloudflare: 3.33.1 → 4.1.0
terraform-provider-external: 2.2.3 → 2.3.1
```
https://registry.terraform.io/providers/cloudflare/cloudflare/latest/docs/guides/version-4-upgrade
I'd appreciate someone double checking that the upgrade is okay.
=> tasks.py: add update-terraform, terraform/flake.lock: Update

secrets.yaml
See https://github.com/nix-community/infra/issues/393#issuecomment-1475243989
bors merge
=> secrets: add shared cloudflare credentials

services/hydra/default.nix
=> hydra: delete old logs periodically

flake.lock, flake.nix
=> flake: drop unused sops-nix input

build04/configuration.nix, ci.nix, flake.nix, roles/common.nix, roles/users.nix, tasks.py
=> flake: drop domain

HOSTS.md, README.md, docs/README.md, roles/builder/README.md, treefmt.nix
=> treefmt: format markdown, docs: various updates

build03/configuration.nix, services/hydra/default.nix
=> services/hydra: pin cachix to 1.3.3

build04/hardware-configuration.nix, flake.lock
=> build04: update for breaking changes in disko

roles/watch-store.nix
This reverts commit 2ffa3d3f1a0d8678df51774fc472b6630228ca7a.
=> Revert "roles/watch-store: always restart"

.github/CONTRIBUTING.md, .github/PULL_REQUEST_TEMPLATE.md, README.md, docs/README.md, services/hound/README.md, terraform/README.md
=> misc docs changes

build02/configuration.nix, build02/nixpkgs-update-backup.nix, build02/secrets.yaml, secrets.yaml
Closes https://github.com/nix-community/infra/issues/541
@Mic92 I copied most of this from your dotfiles as I noticed that you used to have a borgbackup storagebox.
cc @nix-community/admin
=> build02: backup nixpkgs-update logs

secrets.yaml
I had to re-create the account so we have a +1 to the email address. Once an "organization" account is created, they ask you to verify that the company/org exists legally, and you can't switch back to a personal account without re-creating.
=> secrets: add hetzner entry

build01/configuration.nix, build02/configuration.nix, build03/configuration.nix, roles/disko.nix, roles/raid.nix, roles/zfs.nix, tasks.py
```py
def sfdisk_json(host: DeployHost, dev: str) -> List[Any]:
out = host.run(f"sfdisk --json {dev}", stdout=subprocess.PIPE)
data = json.loads(out.stdout)
return data["partitiontable"]["partitions"]
def _format_disks(host: DeployHost, devices: List[str]) -> None:
assert (
len(devices) == 1 or len(devices) == 2
), "we only support single devices or mirror raids at the moment"
for device in devices:
host.run(
f"sgdisk -Z -n 1:2048:4095 -n 2:4096:+2G -N 3 -t 1:ef02 -t 2:8304 -t 3:8304 {device}"
)
if len(devices) == 2:
boot_parts = []
root_parts = []
for dev in devices:
partitions = sfdisk_json(host, dev)
boot_parts.append(partitions[1]["node"])
root_parts.append(f"/dev/disk/by-partuuid/{partitions[2]['uuid'].lower()}")
host.run(
f"mdadm --create --verbose /dev/md127 --raid-devices=2 …
```
=> preparation for switching to disko

secrets.yaml
these are invalid now the servers have been moved to the nix-community account
=> secrets.yaml: remove build{01,03}-admin

build01/configuration.nix, build01/default.nix, build02/configuration.nix, build02/default.nix, build03/configuration.nix, build03/default.nix, build04/configuration.nix, build04/default.nix, flake.nix, roles/common.nix
Reverts nix-community/infra#584
=> Revert "flake: split up per host"

roles/common.nix
This reverts commit c52ccf95edbb6d26ba46ed4a578bca37ba36cd07.
~~Need to wait for https://nixpk.gs/pr-tracker.html?pr=231393 to land in unstable-small.~~
=> Revert "roles/common: pin kernel"

dev/shell.nix, flake.nix
Same as we did for treefmt in https://github.com/nix-community/infra/pull/518.
=> dev/shell: flatten

terraform/cloudflare_nix-community_org.tf, terraform/secrets.yaml
Moved out of https://github.com/nix-community/infra/pull/592.
=> terraform/cloudflare: add darwin02

dev/effect.nix
copied from 428fa510894873cc5ce7bc1e8008224bc0d759cf
=> dev/effect: avoid downloading closure on the deploying machine

hosts/build02/nixpkgs-update-backup.nix, hosts/build02/secrets.yaml, modules/nixos/security.nix, secrets.yaml
this is now under the nix-community hetzner account
=> refactor storage box

dev/effect.nix, devdoc/hosts.md, flake.nix, hosts/build02/configuration.nix, hosts/build03/configuration.nix, hosts/darwin03/configuration.nix, modules/nixos/common/security.nix, modules/nixos/remote-builder/darwin03.nix, secrets.yaml, tasks.py
Depends on https://github.com/nix-community/infra/pull/676
=> darwin03: init

dev/effect.nix, devdoc/hosts.md, hosts/darwin02/configuration.nix, modules/nixos/common/security.nix, secrets.yaml, terraform/cloudflare_nix-community_org.tf
DNS changes need to be applied before merging otherwise the darwin deploy effect will fail.
=> darwin02: scaleway -> hetzner

modules/darwin/common/default.nix
Restrict authorized_keys and disallow password auth.
=> modules/darwin/common: add some ssh settings

flake.nix, hosts/build03/configuration.nix, hosts/build03/secrets.yaml, modules/nixos/github-org-backup.nix
Now that we have access to external storage we could use it to backup the repos.
https://github.com/gabrie30/ghorg
~~Still need to add secrets, I'll do that if we want to move forward with this.~~
=> modules/nixos: github-org-backup 

hosts/build02/configuration.nix
=> build02: remove remote builders

.sops.yaml, dev/effect.nix, hosts/web01/configuration.nix, modules/nixos/cachix-deploy/secrets.yaml, modules/nixos/cachix/secrets.yaml
[Testing cachix deploy on build01](https://github.com/nix-community/infra/pull/688) probably wasn't the best idea, should have tried it on a host that can be a bit flaky.
Needs to be deployed to web01 before the PR is merged.
=> web01: cachix deploy

devdoc/hosts.md
This is an internal document so I don't think we need comments about the hosts as we can just inspect the code and the comments end up outdated anyway.
=> devdoc/hosts.md: update

modules/nixos/community-builder/keys/networkexception, modules/nixos/community-builder/users.nix
Update modules/nixos/community-builder/users.nix
=> builder/users: add networkexception

modules/shared/nix-daemon.nix
=> modules/shared/nix-daemon: revert min-free to 10gb

.github/workflows/fork.yml
Hopefully this will allow us to merge PRs from forks.
Tested in https://github.com/nix-community/infra/pull/794.
=> .github/workflows/fork.yml: fake hercules status for merge queue

flake.nix
Simpler way of restricting the checks to x86_64-linux.
=> flake: refactor checks

.github/workflows/pages.yml, docs/sponsors.md, flake.nix
Mostly copied from https://github.com/actions/starter-workflows/tree/main/pages.
Need to change "deploy from a branch" to "github actions" in https://github.com/nix-community/infra/settings/pages.
=> switch to actions for github pages

.github/workflows/repo-list.yml, dev/treefmt.nix
As we're moving back to actions for now adding a linter for them may be useful.
=> dev/treefmt: add actionlint

flake.lock, flake.nix
Depends on https://github.com/nix-community/infra/pull/836, https://github.com/nix-community/infra/pull/839, https://github.com/nix-community/infra/pull/840
=> flake: remove hercules-ci-effects

modules/darwin/common/default.nix
Can merge this after the next flake update.
=> modules/darwin/common: set timeZone

dev/treefmt.nix, tasks.py
Blocked on https://github.com/NixOS/nixpkgs/pull/253552, needs to go through staging.
https://nixpk.gs/pr-tracker.html?pr=253552
=> dev/treefmt: add mypy for tasks.py

.github/workflows/pages.yml
- this package should always be cached, add max-jobs so job errors if it isn't
- move accept-flake-config to extra_nix_config
=> .github/workflows/pages.yml: various

secrets.yaml
Update email address to use an `admin` alias instead of `admin@nix-community.org`.
=> secrets.yaml: update infra-bot email

modules/nixos/monitoring/alert-rules.nix
Need to bump this a bit now we've changed the nix gc settings.
=> modules/nixos/monitoring/alert-rules: update filesystem_full rules

flake.lock, hosts/build02/nixpkgs-update.nix
Why
===
* The updatescript was not getting the latest information
What changed
===
* Before finding updatescripts to run, update nixpkgs
=> build02: nixpkgs-update: before running the updatescript fetcher, pull latest nixpkgs

hosts/build02/nixpkgs-update.nix
Follow-up to #878.
@ryantm please expedite!
=> build02/nixpkgs-update: quiet the git command in updatescript fetcher

config.yaml, dev/shell.nix, secrets.yaml, tasks.py
I'd imagine that eventually we'd want to move to a password manager but this is enough of an improvement over the current workflow that we can put off making that decision.
https://github.com/getsops/sotp
Unlicensed at the moment, I'll add it to nixpkgs once upstream addresses that.
=> use `sotp` for TOTP secrets

modules/nixos/common/security.nix
Module seems to be broken, nixos test is failing.
=> modules/nixos/common/security: disable fail2ban

.github/workflows/cachix.yml, flake.nix, secrets.yaml
Will use this instead of the previous ssh deployment for darwin once our hercules ci problems are resolved.
=> switch to cachix deploy

.github/settings.yml
- add nix-community-buildbot topic
- remove hercules-ci push permission
=> .github/settings.yml: various

flake.lock, flake.nix, modules/darwin/hercules-ci/default.nix, modules/nixos/hercules-ci/default.nix
Switch to 0.10 agent, can revert this once it is in nixpkgs.
=> switch to upstream hercules ci agent

modules/darwin/community-builder/keys/sgo, modules/darwin/community-builder/users.nix
Hi! I'd like to request access to the darwin community builder. The purpose for this access is primarily to debug and fix perlPackages on Darwin.
=> modules/darwin/community-builder: add user (sgo)

terraform/cloudflare_nix-community_org.tf
Skipped this when I did the initial setup for these hosts and forgot to finish it.
=> terraform/cloudflare: add ipv6 for darwin0{2,3}

flake.nix
https://nixpk.gs/pr-tracker.html?pr=263963
=> flake: re-enable buildbot nixosTest

.github/workflows/flake-updates-input.yml, .github/workflows/flake-updates-nixpkgs-update.yml, .github/workflows/flake-updates.yml
Automates creating a flake update PR for a single input.
=> .github/workflows/flake-updates-input.yml: rename, add input

hosts/build03/configuration.nix, hosts/build03/secrets.yaml, hosts/web01/configuration.nix, hosts/web01/secrets.yaml, modules/nixos/monitoring/telegraf.nix, terraform/cloudflare_nix-community_org.tf
This reverts commit 0fe327bce4c24e9be6e582d70eb77916f28c5dc4.
=> Revert "nur-update: build03 -> web01"

modules/nixos/community-builder/users.nix
Reverts https://github.com/nix-community/infra/pull/735.
=> modules/nixos/community-builder/users: make everyone trusted

.github/workflows/darwin.yml, .github/workflows/pages.yml
Reverts nix-community/infra#978
=> Revert ".github/workflows: run darwin, pages after buildbot completes"

flake.nix
This reverts commit 8d9da7e9a24fac70913e466922e2de87f7fcdcf1.
=> Revert "flake: disable buildbot nixosTest"

docs/community-builder.md, modules/darwin/community-builder/users.nix
https://github.com/nix-community/infra/issues/1007
=> docs/community-builder: add note about darwin keys

modules/darwin/community-builder/keys/sternenseemann, modules/darwin/community-builder/users.nix
Please there is an angry mob of aarch64-darwin users in front of my house that want me to fix aarch64-darwin Haskell issues.
=> darwin/community-builder: add user sternenseemann

.github/workflows/darwin.yml
Sometimes the deploy environment looks like it didn't work but it is just racy, depending on both should address this.
=> .github/workflows/darwin.yml: add collect step

.github/workflows/flake-updates.yml, .github/workflows/repo-list.yml
Added nix-infra-bot back as a collaborator for this repo and added a new token.
=> .github/workflows: re-enable automerge

hosts/build02/supervisor.py
Response to https://github.com/nix-community/infra/pull/833#pullrequestreview-1795523252
=> build02/nixpkgs-update: scramble order of new jobs

hosts/build02/nixpkgs-update.nix, modules/nixos/monitoring/alert-rules.nix, modules/nixos/monitoring/telegraf.nix
Will wait a few days before trying this but I think it should be fine, with the new machine the constraint will likely be if ofborg can keep up with the volume.
=> build02/nixpkgs-update: add more workers

modules/darwin/community-builder/keys/pennae, modules/darwin/community-builder/users.nix
=> darwin/community-builder: add pennae

flake.lock, flake.nix
I've deployed this manually for now.
=> flake: update nixpkgs-update

flake.lock
This authz fix is quite useful: https://github.com/Mic92/buildbot-nix/pull/104
=> bump buildbot-nix

flake.lock, flake.nix, hosts/darwin02/configuration.nix, modules/darwin/hercules-ci/default.nix, modules/nixos/hercules-ci/default.nix
~~https://nixpk.gs/pr-tracker.html?pr=288372~~
~~https://nixpk.gs/pr-tracker.html?pr=279413~~
https://nixpk.gs/pr-tracker.html?pr=294055
=> switch back to nixpkgs hercules ci agent

flake.nix
Not sure what the hercules problem is, I'll pin it for now and take a closer look soon.
=> flake: pin darwin02

hosts/build02/configuration.nix
This reverts commit 487138275cd3c02acc6847ee3c9d7cd2544400fa.
=> Revert "build02: switch to btrfs"

hosts/build02/nixpkgs-update.nix, hosts/build02/packages-with-update-script.nix
I've tested this a couple of times and it seems fine.
=> build02/nixpkgs-update: reuse worker nixpkgs repo for updatescript

hosts/build02/nixpkgs-update.nix
Both of these fetchers are currently broken. https://github.com/nix-community/infra/issues/1179, https://github.com/nix-community/infra/issues/1180
=> build02/nixpkgs-update: disable github and updatescript fetchers

flake.lock, hosts/build02/nixpkgs-update.nix
https://github.com/nix-community/infra/issues/1179, https://github.com/nix-community/infra/issues/1180
=> build02/nixpkgs-update: reenable github and updatescript fetchers

flake.lock, flake.nix
```
msg="Pull from remote 'origin' failed: Get \"https://github.com/nix-community/infra.git/info/refs?service=git-upload-pack\": context deadline exceeded"
```
=> flake: pin comin

modules/darwin/community-builder/keys/annalee, modules/darwin/community-builder/users.nix
This reverts commit c0263ecb840d979cb5c1896255c76c2dc2189ab8.
Github account has been deleted. https://github.com/nix-community/infra/pull/1157
=> Revert "darwin/community-builder: add user annalee"

modules/nixos/disko-raid.nix
This reverts commit 36125d58aaf20d3b3a024890e08aa8c8b16a6019.
=> Revert "modules/nixos/disko-raid: add option for filesystem type"

docs/update-bot.md
=> docs: fix typo

flake.nix, hosts/build01/configuration.nix, modules/nixos/common/default.nix, modules/nixos/disko-zfs.nix
Had issues with mirrored boot so not going to bother with it for now.
@Mic92 This config passes the nixos-anywhere vm-test but can you take a look to make sure the zfs stuff is okay?
=> build01: switch to zfs

hosts/build03/configuration.nix, hosts/darwin02/configuration.nix, modules/darwin/hercules-ci/default.nix
Should be fixed in nixpkgs but this will do for now.
=> modules/darwin/hercules-ci: add security to service path

flake.nix, hosts/build02/nixpkgs-update.nix, hosts/build02/supervisor.py, hosts/build02/supervisor_test.nix, hosts/build02/supervisor_test.py
I looked at packaging/wrapping `supervisor.py` but seems to make it more complicated than is really necessary.
@rhendric Does this look okay?
=> nixpkgs-update supervisor

secrets.yaml
Part of https://github.com/nix-community/infra/issues/984.
=> secrets.yaml: add r-ryantm

flake.lock, flake.nix
Currently using my fork, need to fix and merge a few upstream PRs before we can switch back.
=> flake: switch back to upstream nixpkgs-update

.github/CONTRIBUTING.md
not needed since we switched to buildbot
=> remove CONTRIBUTING.md

secrets.yaml
- **secrets: add oakhost.net**
=> add oakhost

.github/workflows/darwin.yml
- drop user, already set in tasks.py
- share ssh known_hosts
=> .github/workflows/darwin.yml: various

devdoc/hosts.md, docs/community-builder.md, modules/darwin/community-builder/users.nix, modules/shared/known-hosts.nix, secrets.yaml, tasks.py, terraform/cloudflare_nix-community_org.tf
Messy first draft of changes, I'll finish this tomorrow.
Overlaps with https://github.com/nix-community/infra/pull/1255, I'll need to update the hercules secrets so they can be deployed on both machines.
=> darwin01: switch to new hardware

tasks.py
Currently it works for the darwin hosts but I seem to have broken build* when I added the customer user for darwin01.
I'll come back and fix this in a few hours.
=> tasks.py: fix deploy

.editorconfig, dev/treefmt.nix, flake.nix
https://nixpk.gs/pr-tracker.html?pr=315650
=> treefmt: remove pipelines, readd editorconfig

flake.nix
Split off from https://github.com/nix-community/infra/pull/1287.
Basically just tidying up how the checks and packages are handled.
=> flake: refactor

flake.lock, flake.nix
Just pinning this for a few days while upstream is stabilised, I plan to switch to the github app in a week or so.
=> flake: pin buildbot-nix

hosts/darwin01/configuration.nix, hosts/darwin02/configuration.nix, hosts/darwin03/configuration.nix
seems to have been broken by nix 2.18.4
=> disable sandbox on darwin hosts

flake.lock
% nix build --inputs-from . nixpkgs#openssh
% realpath ./result/bin/ssh
/nix/store/1kbx7ckf6ixfh4yvyhk2325qhyjvxnfw-openssh-9.8p1/bin/ssh
=> update nixpkgs to include openssh update

modules/nixos/hydra.nix
This reverts commit 78a1f03f2eb96da4386ceef282c565098190f187.
=> Revert "modules/nixos/hydra: remove secret"

modules/nixos/buildbot.nix
This allows me to better debug permission issues
=> buildbot: remove myself as an admin

hosts/build02/configuration.nix, hosts/build03/configuration.nix
=> build02, build03: set gc to 500gb

tasks.py
supported for updatekeys since 3.9.0
=> tasks.py: switch to glob for update-sops-files

hosts/build02/configuration.nix
fixes https://github.com/nix-community/infra/issues/1362
=> different workaround for zpool import

flake.lock, flake.nix, modules/nixos/buildbot.nix
This reverts commit 57e60f4da8b26699fb8e1593c4b09d5d56bdfff9.
I fixed zero retries in https://github.com/nix-community/buildbot-nix/pull/218 and tested it in https://github.com/Mic92/dotfiles/pull/1188
=> Revert "flake: pin buildbot"

modules/nixos/community-builder/keys/thecomputerguy, modules/nixos/community-builder/users.nix
I've moved away from x86_64 to aarch64 so I can't test things on x86_64 myself anymore. Having access would be great as one of the maintainers for LLVM, I already have access to the aarch64 community box.
=> builder/users: add thecomputerguy

modules/darwin/common/default.nix
=> modules/darwin/common: remove nix.gc.user

flake.lock, flake.nix
Cherry pick of https://github.com/nix-community/buildbot-nix/commit/6006d815b6a577c0b245b16444b0596576cf000c.
=> flake: buildbot-nix: skipped-build-workers

flake.lock, modules/nixos/buildbot.nix
This reverts commit 717fb28b0a2c5c34d54f6d72bc47ccf9b43805bf.
=> Revert "modules/nixos/buildbot: disable cachix"

modules/darwin/common/default.nix, modules/darwin/common/users.nix, modules/nixos/common/default.nix, modules/nixos/common/users.nix, modules/nixos/community-builder/users.nix
Just a minor refactor in preparation for other changes.
=> modules/darwin,nixos: refactor users

terraform/cloudflare_nix-community_org.tf
https://github.com/cloudflare/terraform-provider-cloudflare/releases/tag/v4.39.0
=> terraform/cloudflare: value -> content

modules/nixos/common/update.bash
=> modules/nixos/common/update.bash: return -> exit

flake.lock, flake.nix
We'll be using these eventually so I'm adding them in advance so I can work on them without having to keep fixing merge conflicts.
=> flake: add hercules-ci-effects, cgroup-exporter, nixos-facter-modules

flake.nix, hosts/build02/default.nix, hosts/build02/nixpkgs-update.nix, hosts/build03/default.nix, hosts/web02/default.nix, modules/nixos/buildbot.nix, modules/nixos/hydra.nix, modules/nixos/monitoring/default.nix, modules/nixos/nginx.nix, modules/nixos/nur-update.nix
~~Maybe quic as well?~~ Will look at quic in another PR.
~~`net.ipv4.tcp_fastopen=3` ?~~
=> modules/nixos: add nginx

modules/nixos/community-builder/keys/raboof, modules/nixos/community-builder/users.nix
mainly for one-off tests, such as seeing if I can further reproduce https://github.com/python/cpython/issues/124924
=> Add raboof

.github/pull_request_template.md, modules/shared/community-builder.nix
Closes https://github.com/nix-community/infra/issues/1147.
=> add PR template and motd for matrix room

flake.nix
This reverts commit 1ed58314409be025dba0a9e02967e3691d621d48.
=> Revert "flake: fix docs"

docs/package-sets.md, terraform/hydra-projects.tf
=> docs: refactor, add cuda stable to package sets

docs/open-collective.md
=> docs/open-collective: add noscript

terraform/cloudflare.tf, terraform/cloudflare_nix-community_org.tf
=> terraform/cloudflare: refactor

devdoc/hosts.md, tasks.py
=> tasks.py: various

flake.lock, modules/darwin/community-builder/users.nix
=> update nix-darwin, remove users.forceRecreate

modules/nixos/hydra.nix
=> modules/nixos/hydra: refactor

hosts/build03/postgresql.nix
The performance improvements seem to make it worth upgrading.
=> build03: postgresql_16 -> postgresql_17

terraform/hydra-projects.tf
https://github.com/nix-community/infra/pull/1538
=> terraform/hydra-projects: add microvm.nix

hosts/build02/nixpkgs-update.nix, hosts/build02/worker.bash
=> nixpkgs-update: move worker to bash script

modules/nixos/community-builder/users.nix
- align with darwin/community-builder
- remove unused hashedPassword, maybeWheel options
=> modules/nixos/community-builder: refactor users

flake.nix, hosts/build02/nixpkgs-update-backup.nix, modules/nixos/backup.nix, modules/nixos/github-org-backup.nix, modules/shared/known-hosts.nix
=> modules/nixos: add backup

hosts/build02/packages-with-update-script.nix
=> nixpkgs-update: disallow aliases in updatescript fetcher

hosts/build02/nixpkgs-update-backup.nix, modules/nixos/backup.nix, modules/nixos/github-org-backup.nix, modules/nixos/monitoring/alert-rules.nix
=> modules/nixos/backup: add hourly, nixpkgs-update: switch to hourly backups

dev/treefmt.nix
=> treefmt: remove redundant flag, exclude symlinked file

hosts/build02/nixpkgs-update.nix, hosts/web02/gandi.nix, modules/nixos/hydra.nix, modules/nixos/monitoring/grafana.nix, modules/nixos/monitoring/matrix-hook.nix, modules/nixos/monitoring/prometheus.nix, modules/nixos/nur-update.nix
This gives us eval time error checking.
This one isn't defined in nixpkgs so it needs to remain as it is.
https://github.com/nix-community/infra/blob/06c99f6ef156c8910f94f33a400c8ebe5094c82f/modules/nixos/common/update.nix#L25
=> use systemd unit name attribute

modules/nixos/backup.nix
=> modules/nixos/backup: set restart on-failure

modules/shared/nix-daemon.nix
=> modules/shared/nix-daemon: set max-silent-time, timeout

docs/package-sets.md, terraform/hydra-nixpkgs.tf
https://hydra.nix-community.org/jobset/nixpkgs/unfree-redist-stable
=> terraform/hydra-nixpkgs: add unfree-redist-stable

hosts/build03/builders.nix, hosts/build03/default.nix, hosts/build04/default.nix, hosts/darwin02/default.nix, modules/darwin/ci-builder.nix, modules/nixos/ci-builder.nix, modules/shared/ci-builder.nix, modules/shared/remote-builder.nix
https://github.com/nix-community/infra/pull/1573 but only for the CI hosts.
~~Might refactor the builder imports into one and use options instead?~~ I'll leave this for now.
=> modules/shared/ci-builder: set max-silent-time, timeout

modules/nixos/hydra.nix
=> modules/nixos/hydra: disable services

modules/nixos/common/update.bash
=> modules/nixos/common: set narinfo-cache-negative-ttl for update

flake.nix
=> flake: sort inputs

modules/nixos/hydra.nix
needed to create new declarative jobsets
=> modules/nixos/hydra: re-enable hydra-notify

modules/shared/ci-builder.nix
Workaround for https://github.com/nix-community/infra/issues/1459#issuecomment-2507146996.
=> modules/shared/ci-builder: increase max-silent-time

hosts/build01/default.nix, hosts/build02/default.nix, modules/nixos/common/default.nix
=> build01,build02: enable cgroups, modules/nixos/common: increase zram to 100%

docs/package-sets.md, modules/nixos/hydra.nix, terraform/hydra-nixpkgs.tf
I'll experiment with this later after `unfree-redist` is merged, not sure if we really have the cycles to spare for it with only the one darwin CI builder.
https://hydra.nix-community.org/jobset/nixpkgs/unfree-redist-darwin
=> terraform/hydra-nixpkgs: add unfree-redist-darwin

hosts/build03/builders.nix
Currently we check that each host is reachable via ssh from web02 but we should also be checking that the remote builders are reachable from the CI master.
=> build03: check remote builder ssh connection

hosts/build02/nixpkgs-update.nix, modules/nixos/monitoring/matrix-hook.nix, modules/nixos/monitoring/prometheus.nix
https://github.com/NixOS/nixpkgs/commit/b2e99477cd7f6450a600db7f2fff07cf2cc1bd69
=> update network-online target

modules/nixos/common/update.bash, modules/nixos/common/update.nix
After we've tested this here for a couple of weeks I'll add it to the update diff in srvos.
=> modules/nixos/common/update: use grub.extraInstallCommands for boot diff

hosts/build02/filter.sed, hosts/build02/nixpkgs-update.nix
=> nixpkgs-update: various

modules/nixos/buildbot.nix
Allows us to reuse the worker password secret and makes adjusting the worker easier.
=> modules/nixos/buildbot: use template for workersFile, set WORKER_COUNT explictly

modules/shared/telegraf.nix
=> modules/shared/telegraf: use config.nix.package

hosts/build03/default.nix
=> build03: network-online wantedBy multi-user

flake.nix, modules/shared/community-builder.nix
=> Revert "disable docs-linkcheck", "modules/shared/community-builder: disable kitty on darwin"

modules/nixos/monitoring/telegraf.nix
=> modules/nixos/monitoring: remove ofborg

.sops.yaml, docs/community-builder.md, modules/secrets/community-builder.yaml, modules/shared/known-hosts.nix, sops.json
=> darwin01: update host key

modules/nixos/common/builder.nix
This is enabled in nixos/infra.
https://docs.kernel.org/admin-guide/mm/ksm.html
=> modules/nixos/common/builder: enable kernel samepage merging

modules/darwin/common/sops-nix.nix
=> modules/darwin/common/sops-nix: disable gnupg

docs/community-builder.md, modules/darwin/community-builder/users.nix
Closes https://github.com/nix-community/infra/issues/1007
=> Revert "docs/community-builder: add note about darwin keys"

flake.lock, flake.nix, hosts/build02/nixpkgs-update.nix
=> nixpkgs-update: use tools from $PATH, pin nixpkgs-review

flake.lock, flake.nix
=> flake: nixos-facter-modules: numtide -> nix-community

hosts/build05/default.nix
Already running this on build01. https://github.com/nix-community/infra/pull/1599
=> build05: switch to zfs_unstable

modules/nixos/community-builder/users.nix
This now matches the instructions for the darwin community builders.
=> modules/nixos/community-builder/users: update comment

modules/darwin/community-builder/keys/booxter, modules/darwin/community-builder/users.nix
Requesting access to darwin community-builders for now since I'd like to reproduce a [failure](https://github.com/NixOS/nixpkgs/pull/374698#issuecomment-2599994302) in llama-cpp-python that I can't otherwise reproduce on my own darwin machine.
=> users: add booxter

hosts/build01/default.nix, hosts/build05/default.nix
This reverts commit a606396fa14cb1110f0b5374edcdd6d438fdc718.
=> Revert "build01, build05: switch to 6.12 kernel"

hosts/darwin01/default.nix
halve the number of cores and reduce max-jobs a little.
=> darwin01: limit cores/max-jobs

modules/shared/community-builder.nix
=> modules/shared/community-builder: disable grml zsh prompt on darwin

hosts/build01/default.nix
=> build01: test zram writebackDevice

hosts/build01/default.nix
This reverts commit 79f87ebdabf7fe41f67f42144be5ab4b6c1f910f.
=> Revert "build01: test zram writebackDevice"

flake.lock, hosts/build02/filter.sed
=> nixpkgs-update: filter lua packages

dev/docs.nix
=> docs: use mkdocs-redirects only

devdoc/darwin.md
I don't want to manage the macos hosts with MDM but maybe it will be inevitable.
=> devdoc/darwin: apple intelligence

dev/packages.nix, modules/shared/community-builder.nix
=> modules/shared/community-builder: enable grml on darwin

devdoc/darwin.md, flake.lock, flake.nix, tasks.py
Part of https://github.com/nix-community/infra/issues/813
=> darwin: sudo activation

dev/treefmt.nix, flake.nix
=> treefmt: add keep-sorted

modules/darwin/community-builder/keys/thecomputerguy, modules/darwin/community-builder/users.nix
Similar to #1386, I'd like to have access to Darwin.
=> darwin/community-builder: add thecomputerguy

flake.lock, flake.nix, modules/nixos/cgroups.nix
Waiting for pkgs.nix to be updated in nixpkgs.
https://nixpkgs-tracker.ocfox.me/?pr=396442
=> switch back to pkgs.nix

flake.nix
https://github.com/nix-community/infra/pull/1768#issuecomment-2788784442
Broken and they also seem to get stuck and need to be cancelled manually.
=> flake: disable darwin effect deploy

flake.lock, flake.nix, modules/nixos/buildbot.nix
=> Revert "flake: pin buildbot-nix"

flake.lock, flake.nix
=> Revert "flake: disable darwin effect deploy" 

modules/nixos/hydra.nix
=> modules/nixos/hydra: avoid restarting hydra when changing buildMachinesFiles

modules/darwin/community-builder/keys/lukegb, modules/darwin/community-builder/users.nix, modules/nixos/community-builder/keys/lukegb, modules/nixos/community-builder/users.nix
=> {darwin,nixos}/community-builder: add lukegb

dev/treefmt.nix
=> treefmt: fix mypy

modules/shared/host-info.bash, modules/shared/telegraf.nix
=> modules/shared: fix host-info

modules/nixos/community-builder/users.nix
=> community-builder: set shell to fish for perchun

dev/treefmt.nix, docs/index.md, docs/sponsors.md
=> treefmt: drop prettier, switch to mdformat, mdformat-mkdocs, yamlfmt

dev/docs.nix, hosts/build01/default.nix, hosts/build02/default.nix, hosts/build03/builders.nix, hosts/build03/default.nix, hosts/build04/default.nix, hosts/build05/default.nix, modules/nixos/buildbot.nix, modules/nixos/cgroups.nix, modules/nixos/common/builder.nix, modules/nixos/hydra.nix, modules/shared/nix-daemon.nix
Added this for the sake of completeness in https://github.com/nix-community/infra/pull/1507 but now seems to be slightly broken due to changes in nixpkgs. I don't think anyone needs it so for now I'll just rip it out and redo it later.
=> modules/nixos: drop extra-platforms & gccarch, fix system-features

hosts/build02/filter.sed
=> nixpkgs-update: switch to python3Packages

modules/nixos/cgroups.nix, modules/shared/ci-builder.nix
=> modules/nixos/cgroups: patch nix

modules/shared/host-info.bash
=> modules/shared/host-info: show reboot is scheduled

dev/packages.nix, docs/community-builders.md, modules/darwin/community-builder/default.nix, modules/darwin/community-builder/users.nix
=> security keys

docs/dns.md, docs/infrastructure.md, docs/monitoring.md, docs/nur-update.md, docs/other-services.md, mkdocs.yml
Keeps the services most people will care about at the top level and makes the list of services shorter.
=> docs: consolidate minor services into one page

.sops.yaml, dev/sops.nix, flake.nix, tasks.py
Split this off from https://github.com/nix-community/infra/pull/1794.
Failing on outdated `.sops.yaml`: https://buildbot.nix-community.org/#/builders/3998/builds/3/steps/1/logs/stdio
Failing on outdated yaml secret files: https://buildbot.nix-community.org/#/builders/3998/builds/4/steps/1/logs/stdio
Passing check: https://buildbot.nix-community.org/#/builders/3998/builds/6/steps/1/logs/stdio
=> add sops secrets check

terraform/hydra-nixpkgs.tf
=> terraform/hydra-nixpkgs: bump stable to 25.05

flake.lock, flake.nix
=> flake: switch back to upstream nix-darwin

flake.lock, flake.nix
=> flake: switch back to upstream hercules-ci-effects

terraform/hydra-nixpkgs.tf
=> terraform/hydra-nixpkgs: refactor

dnscontrol/dnsconfig.js, flake.lock, flake.nix, hosts/build03/cache.nix, hosts/build03/default.nix, hosts/build03/secrets.yaml, hosts/freebsd/configuration.nix, modules/shared/nix-daemon.nix
=> build03: add snix-cache, queued-build-hook

terraform/hydra-nixpkgs.tf
=> terraform/hydra-nixpkgs: decrease check_interval for unfree_redist_full

flake.lock, flake.nix, hosts/build03/cache.nix, hosts/build03/secrets.yaml, hosts/freebsd/configuration.nix, modules/shared/nix-daemon.nix
Intented to be a somewhat private fallback for paths that still exist on build03 but may have been removed from cachix.
=> build03: add harmonia cache

flake.lock, modules/darwin/common/network.nix
=> modules/darwin/common: system.defaults.alf -> networking.applicationFirewall

modules/shared/community-builder.nix
=> modules/shared/community-builder: further reduce cores

hosts/build02/default.nix, hosts/build02/filter.sed, hosts/build02/nixpkgs-update.nix
=> build02, nixpkgs-update: various

hosts/build02/filter.sed
=> nixpkgs-update: filter more packages

dnscontrol/dnsconfig.js
=> dnscontrol: add nl.meet

hosts/build02/default.nix, tasks.py
I think auto-optimise-store is too efficient on this machine, gc is very slow (days compared to hours on the others), try running without it a few weeks.
=> build02: disable auto-optimise-store

hydra/bsd.nix, terraform/hydra-nixpkgs.tf
=> terraform/hydra-nixpkgs: add bsd

modules/nixos/disko-zfs.nix
=> modules/nixos/disko-zfs: set zfs_txg_timeout

modules/darwin/community-builder/keys/mdaniels5757, modules/darwin/community-builder/users.nix, modules/nixos/community-builder/keys/mdaniels5757, modules/nixos/community-builder/users.nix
This would be useful to help me test some large builds that exceed GitHub Actions' limits, and to better be able to debug Darwin issues when they arise.
=> {darwin,nixos}/community-builder: add user mdaniels5757

modules/nixos/community-builder/users.nix
=> nixos/community-builder: set default shell for mdaniels5757

modules/nixos/community-builder/keys/sternenseemann, modules/nixos/community-builder/users.nix
Same as https://github.com/nix-community/infra/pull/1028.
=> nixos/community-builder: add sternenseemann

modules/darwin/common/telegraf.nix
=> modules/darwin/common: fix telegraf 1.36.1

modules/nixos/common/security.nix, modules/shared/nix-daemon.nix
=> modules/nixos/common: switch to nftables

hosts/build01/default.nix, hosts/build05/default.nix, modules/nixos/clang-lto-kernel.nix
=> modules/nixos: add clang-lto-kernel
